/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkArea.Faculty;

import Business.Business;
import Business.Course.Course;
import Business.Profiles.ProfessorProfile;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Bhagya
 */
public class ManageIndividualCourseFacultyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageIndividualCourseFacultyJPanel
     */
    JPanel workArea;
    Business business;
    ProfessorProfile professorProfile;
    public ManageIndividualCourseFacultyJPanel(JPanel workArea, Business business, ProfessorProfile professorProfile) {
        initComponents();
        this.workArea = workArea;
        this.business = business;
        this.professorProfile = professorProfile;
        System.out.println(professorProfile.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCourseId = new javax.swing.JTextField();
        txtCredits = new javax.swing.JTextField();
        txtDayAndTime = new javax.swing.JTextField();
        txtAvailablePrograms = new javax.swing.JTextField();
        lblCourseId = new javax.swing.JLabel();
        txtTerm = new javax.swing.JTextField();
        lblCourseName = new javax.swing.JLabel();
        btnAddCourse = new javax.swing.JButton();
        lblCredits = new javax.swing.JLabel();
        lblDayAndTime = new javax.swing.JLabel();
        lblProgramsFor = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblTerm = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        txtCrn = new javax.swing.JTextField();
        lblCrn = new javax.swing.JLabel();
        lblRoomBuilding = new javax.swing.JLabel();
        txtRoomBuilding = new javax.swing.JTextField();
        lblProgram = new javax.swing.JLabel();
        txtProgram = new javax.swing.JTextField();
        lblDegreesFor = new javax.swing.JLabel();
        txtDegreesFor = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage your course as Faculty");

        lblCourseId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCourseId.setText("Course Id:");

        lblCourseName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCourseName.setText("Course Name : ");

        btnAddCourse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddCourse.setText("Add Course");
        btnAddCourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });

        lblCredits.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCredits.setText("Credits: ");

        lblDayAndTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDayAndTime.setText("Class Day and Time:");

        lblProgramsFor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProgramsFor.setText("Available for Programs:");

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTerm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTerm.setText("Term : ");

        lblCrn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCrn.setText("CRN:");

        lblRoomBuilding.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRoomBuilding.setText("Room and Building Location:");

        lblProgram.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProgram.setText("Program:");

        txtProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProgramActionPerformed(evt);
            }
        });

        lblDegreesFor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDegreesFor.setText("Available for Degree:");

        txtDegreesFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDegreesForActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(199, 199, 199)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblTerm)
                                            .addComponent(lblRoomBuilding))
                                        .addGap(50, 50, 50)
                                        .addComponent(txtRoomBuilding))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(44, 44, 44)
                                                    .addComponent(lblDegreesFor))
                                                .addComponent(lblProgram, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtProgram)
                                            .addComponent(txtDegreesFor)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblDayAndTime)
                                            .addComponent(lblProgramsFor, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCredits)
                                            .addComponent(lblCourseId)
                                            .addComponent(lblCourseName)
                                            .addComponent(lblCrn))
                                        .addGap(52, 52, 52)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCourseId)
                                            .addComponent(txtCredits)
                                            .addComponent(txtDayAndTime)
                                            .addComponent(txtAvailablePrograms)
                                            .addComponent(txtTerm)
                                            .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCrn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 370, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCrn)
                    .addComponent(txtCrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseName)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseId)
                    .addComponent(txtCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCredits))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDayAndTime)
                    .addComponent(txtDayAndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgramsFor)
                    .addComponent(txtAvailablePrograms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTerm, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoomBuilding)
                    .addComponent(txtRoomBuilding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProgram, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDegreesFor)
                    .addComponent(txtDegreesFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCourse)
                    .addComponent(btnBack))
                .addContainerGap(183, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProgramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProgramActionPerformed

    private void txtDegreesForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDegreesForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDegreesForActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
        Component[] componentArray = workArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageCourseJPanel panel = (ManageCourseJPanel) component;
        panel.populateTable();
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        // TODO add your handling code here:
        String courseId = txtCourseId.getText();
        String courseName = txtCourseName.getText();
        String crn = txtCrn.getText();
        String availablePrograms = txtAvailablePrograms.getText();
        String dayAndTime = txtDayAndTime.getText();
        String credits = txtCredits.getText();
        String degreesFor = txtDegreesFor.getText();
        String program = txtProgram.getText();
        String roomAndBuilding = txtRoomBuilding.getText();
        String term = txtTerm.getText();
        
        String[] availPrograms = availablePrograms.split(",");
        ArrayList<String> availableProgramsList = new ArrayList<>(Arrays.asList(availPrograms));
        
        Course course = new Course();
        course.setCourseId(courseId);
        course.setCrn(crn);
        course.setCourseName(courseName);
        course.setClassDayAndTime(dayAndTime);
        course.setCourseAvailableforPrograms(availableProgramsList);
        course.setCredits(credits);
        course.setOfferingDegree(degreesFor);
        course.setOfferingTerm(term);
        course.setProgram(program);
        course.setRoomAndBuildingLocation(roomAndBuilding);
        course.setProfName(professorProfile.getFirstName()+" "+professorProfile.getLastName());
        course.setProfId(professorProfile.getProfId());
        course.setProfRating(null);
        
        professorProfile.addCourseOffered(course);
        
//        System.out.println(professorProfile.toString());
//        if(!courseAdded){
//            JOptionPane.showMessageDialog(null, "Course NOT added!");
//        }
//        else{
//            JOptionPane.showMessageDialog(null, "Course Added Successfully by professor " + professorProfile.getFirstName()+"!");
//        }
        JOptionPane.showMessageDialog(null, "Course Added Successfully by professor " + professorProfile.getFirstName()+"!");
    }//GEN-LAST:event_btnAddCourseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCourseId;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblCredits;
    private javax.swing.JLabel lblCrn;
    private javax.swing.JLabel lblDayAndTime;
    private javax.swing.JLabel lblDegreesFor;
    private javax.swing.JLabel lblProgram;
    private javax.swing.JLabel lblProgramsFor;
    private javax.swing.JLabel lblRoomBuilding;
    private javax.swing.JLabel lblTerm;
    private javax.swing.JTextField txtAvailablePrograms;
    private javax.swing.JTextField txtCourseId;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCredits;
    private javax.swing.JTextField txtCrn;
    private javax.swing.JTextField txtDayAndTime;
    private javax.swing.JTextField txtDegreesFor;
    private javax.swing.JTextField txtProgram;
    private javax.swing.JTextField txtRoomBuilding;
    private javax.swing.JTextField txtTerm;
    // End of variables declaration//GEN-END:variables
}
