/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkArea.Faculty;

import Business.Business;
import Business.Course.Course;
import Business.Course.CourseGrading;
import Business.Profiles.ProfessorProfile;
import Business.Profiles.StudentProfile;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Admin
 */
public class PerformanceReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PerformanceReportJPanel
     */
    

    /**
     * Creates new form PerformanceReportJPanel
     */
    JPanel workArea;
    Business business;
    ProfessorProfile professorProfile;
    public PerformanceReportJPanel(JPanel workArea, Business business, ProfessorProfile professorProfile) {
        initComponents();
        this.workArea=workArea;
        this.business=business;
        this.professorProfile = professorProfile;
        populateTable();
    }
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblAnalysis.getModel();
        dtm.setRowCount(0);
        
        for(StudentProfile sp : professorProfile.getStudentList()){
            for(Course c : sp.getCoursesTaken()){
                for(CourseGrading cg : c.getCourseGradeList()){
                    Object row [] = new Object[5];
                    row[0] = sp;
                    row[1] = sp.getMajor();
                    row[2] = sp.getMinor();
                    row[3] = cg.getGpa();
                    
                    dtm.addRow(row);
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnalysis = new javax.swing.JTable();
        btnAnalysis = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));

        headingJLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        headingJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingJLabel.setText("Student Analysis Report Panel");

        tblAnalysis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student", "Major", "Minor", "Gpa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAnalysis);

        btnAnalysis.setBackground(new java.awt.Color(204, 255, 204));
        btnAnalysis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAnalysis.setText("Analyze Student Performances");
        btnAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalysisActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(204, 255, 204));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headingJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 118, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAnalysis))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnalysis, btnBack});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(headingJLabel)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnalysis)
                    .addComponent(btnBack))
                .addContainerGap(224, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAnalysis, btnBack});

    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalysisActionPerformed
        // TODO add your handling code here:
        
        int students95=0;
        int students90=0;
        int students85=0;
        int students80=0;
        int students70=0;
        int studentsF=0;
        for(StudentProfile sp : business.getStudentDirectory().getStudentList()){
            for(Course c : sp.getCoursesTaken()){
                for(CourseGrading cg : c.getCourseGradeList()){
                    if(c.getProfId().equals(professorProfile.getProfId())){
                        if(cg.getFinalGrade().equals("A"))
                            students95++;
                        if(cg.getFinalGrade().equals("A-"))
                            students90++;
                        if(cg.getFinalGrade().equals("B+"))
                            students85++;
                        if(cg.getFinalGrade().equals("B"))
                            students80++;
                        if(cg.getFinalGrade().equals("B-"))
                            students70++;
                        if(cg.getFinalGrade().equals("F"))
                            studentsF++;
                    }
                }
            }
        }
        
        DefaultCategoryDataset barchartdata = new DefaultCategoryDataset();
        barchartdata.setValue(students95, "Number of Students", "A Grade");
        barchartdata.setValue(students90, "Number of Students", "A- Grade");
        barchartdata.setValue(students85, "Number of Students", "B+ Grade");
        barchartdata.setValue(students80, "Number of Students", "B Grade");
        barchartdata.setValue(students70, "Number of Students", "B- Grade");
        barchartdata.setValue(studentsF, "Number of Students", "F Grade");
        JFreeChart barchart = ChartFactory.createAreaChart("Grades", "Grade", "Number of Students", barchartdata, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot barchrt = barchart.getCategoryPlot();
        ChartPanel barPanel = new ChartPanel(barchart);
        workArea.removeAll();
        workArea.add(barPanel, BorderLayout.CENTER);
        workArea.validate();
    }//GEN-LAST:event_btnAnalysisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalysis;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel headingJLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAnalysis;
    // End of variables declaration//GEN-END:variables
}
