/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.Main.WorkSpaceProfiles;

import MarketingManagement.MarketingPersonProfile;
import TheBusiness.Business.Business;
import UserInterface.ManageTheBusiness.ManageTheBusinessJPanel;
import UserInterface.ProductManagement.ManageSuppliersJPanel;
import UserInterface.MarketingManagerWorkArea.CustomerManageMarketingJPanel;
import UserInterface.MarketingManagerWorkArea.ManagePricesMarketingPersonJPanel;
import UserInterface.MarketingManagerWorkArea.PerformanceReportJMarketingPersonJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class MarketingManagerWorkAreaJPanel1 extends javax.swing.JPanel {

    JPanel workArea;
    Business business;
    MarketingPersonProfile marketingPersonProfile;
    /**
     * Creates new form UnitRiskWorkArea
     */

    public MarketingManagerWorkAreaJPanel1(JPanel workArea, Business business, MarketingPersonProfile marketingPersonProfile) {

        this.business = business;
        this.workArea = workArea;
        this.marketingPersonProfile = marketingPersonProfile;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageMarket = new javax.swing.JButton();
        btnManageChannels = new javax.swing.JButton();
        btnManagePrices = new javax.swing.JButton();
        btnPerformanceReports = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnServeCustomer = new javax.swing.JButton();
        customerNameTextField = new javax.swing.JTextField();
        lblCustomer = new javax.swing.JLabel();

        setForeground(new java.awt.Color(51, 51, 51));

        btnManageMarket.setBackground(new java.awt.Color(102, 153, 255));
        btnManageMarket.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnManageMarket.setForeground(new java.awt.Color(255, 255, 255));
        btnManageMarket.setText("Manage Markets");
        btnManageMarket.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageMarket.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageMarket.setMinimumSize(new java.awt.Dimension(20, 23));
        btnManageMarket.setPreferredSize(new java.awt.Dimension(240, 30));
        btnManageMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMarketIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnManageChannels.setBackground(new java.awt.Color(102, 153, 255));
        btnManageChannels.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnManageChannels.setForeground(new java.awt.Color(255, 255, 255));
        btnManageChannels.setText("Manage Channels");
        btnManageChannels.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageChannels.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageChannels.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageChannels.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageChannels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageChannelsActionPerformed(evt);
            }
        });

        btnManagePrices.setBackground(new java.awt.Color(102, 153, 255));
        btnManagePrices.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnManagePrices.setForeground(new java.awt.Color(255, 255, 255));
        btnManagePrices.setText("Manage Prices");
        btnManagePrices.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManagePrices.setMaximumSize(new java.awt.Dimension(145, 40));
        btnManagePrices.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManagePrices.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManagePrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePricesIdentifyEventsActionPerformed(evt);
            }
        });

        btnPerformanceReports.setBackground(new java.awt.Color(102, 153, 255));
        btnPerformanceReports.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPerformanceReports.setForeground(new java.awt.Color(255, 255, 255));
        btnPerformanceReports.setText("Performance Reports");
        btnPerformanceReports.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPerformanceReports.setMaximumSize(new java.awt.Dimension(200, 40));
        btnPerformanceReports.setMinimumSize(new java.awt.Dimension(20, 20));
        btnPerformanceReports.setPreferredSize(new java.awt.Dimension(240, 25));
        btnPerformanceReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerformanceReportsActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Marketing ");

        btnServeCustomer.setBackground(new java.awt.Color(102, 153, 255));
        btnServeCustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnServeCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnServeCustomer.setText("Serve Customer");
        btnServeCustomer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnServeCustomer.setMaximumSize(new java.awt.Dimension(200, 40));
        btnServeCustomer.setMinimumSize(new java.awt.Dimension(20, 23));
        btnServeCustomer.setPreferredSize(new java.awt.Dimension(240, 30));
        btnServeCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServeCustomerIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        customerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameTextFieldActionPerformed(evt);
            }
        });

        lblCustomer.setText("Customer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(292, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnManagePrices, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnPerformanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnServeCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnManageMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnManageChannels, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(279, 279, 279))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(lblCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageChannels, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnServeCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManagePrices, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerformanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(390, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageMarketIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMarketIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:

        ManageTheBusinessJPanel panel = new ManageTheBusinessJPanel(workArea, business);
        workArea.add("ManageTheBusinessJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);

    }//GEN-LAST:event_btnManageMarketIdentifyResourceAssetsActionPerformed

    private void btnManageChannelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageChannelsActionPerformed
        // TODO add your handling code here:

        ManageSuppliersJPanel panel = new ManageSuppliersJPanel(workArea, business);
        workArea.add("ManageSuppliersJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);


    }//GEN-LAST:event_btnManageChannelsActionPerformed

    private void btnManagePricesIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePricesIdentifyEventsActionPerformed
        // TODO add your handling code here:
        ManagePricesMarketingPersonJPanel panel = new ManagePricesMarketingPersonJPanel(workArea, business);
        workArea.add("ManagePricesMarketingPersonJPanel", panel );
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
        
}//GEN-LAST:event_btnManagePricesIdentifyEventsActionPerformed

    private void btnPerformanceReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerformanceReportsActionPerformed
        // TODO add your handling code here:
        PerformanceReportJMarketingPersonJPanel panel = new PerformanceReportJMarketingPersonJPanel(workArea, business);
        workArea.add("PerformanceReportJMarketingPersonJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
}//GEN-LAST:event_btnPerformanceReportsActionPerformed

    private void btnServeCustomerIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServeCustomerIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        CustomerManageMarketingJPanel panel = new CustomerManageMarketingJPanel(workArea, business, marketingPersonProfile);
        workArea.add("CustomerManageMarketingJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnServeCustomerIdentifyResourceAssetsActionPerformed

    private void customerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageChannels;
    private javax.swing.JButton btnManageMarket;
    private javax.swing.JButton btnManagePrices;
    private javax.swing.JButton btnPerformanceReports;
    private javax.swing.JButton btnServeCustomer;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

}
