/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.Main.WorkSpaceProfiles;

import TheBusiness.Business.Business;
import TheBusiness.CustomerManagement.CustomerProfile;
import TheBusiness.SalesManagement.SalesPersonProfile;
import UserInterface.Main.WorkSpaceProfiles.OrderManagement.ManageSalesPersonOrders;
import UserInterface.Main.WorkSpaceProfiles.OrderManagement.ProcessOrder;
import UserInterface.ManageCustomerProfile.ManageCustomerProfileJPanel;
import UserInterface.SalesPersonWorkAreas.SalesPersonPerformanceReportJPanel;
import UserInterface.SalesPersonWorkAreas.SalesPersonReviewComissionJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class SalesPersonWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel workArea;
    Business business;
    SalesPersonProfile salesPerson;

    /**
     * Creates new form UnitRiskWorkArea
     * @param business
     * @param spp
     * @param workArea
     */

    public SalesPersonWorkAreaJPanel(JPanel workArea, Business business, SalesPersonProfile spp) {

        this.business = business;
        this.workArea = workArea;
        salesPerson = spp;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnServeCustomers = new javax.swing.JButton();
        btnManageProfile = new javax.swing.JButton();
        btnReviewOSH = new javax.swing.JButton();
        btnReviewComission = new javax.swing.JButton();
        btnPerformanceReports = new javax.swing.JButton();
        customerNameTextField = new javax.swing.JTextField();
        lblCustomer = new javax.swing.JLabel();

        setForeground(new java.awt.Color(51, 51, 51));

        btnServeCustomers.setBackground(new java.awt.Color(102, 153, 255));
        btnServeCustomers.setFont(getFont());
        btnServeCustomers.setForeground(new java.awt.Color(255, 255, 255));
        btnServeCustomers.setText("Serve Customers");
        btnServeCustomers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnServeCustomers.setMaximumSize(new java.awt.Dimension(200, 40));
        btnServeCustomers.setMinimumSize(new java.awt.Dimension(20, 23));
        btnServeCustomers.setPreferredSize(new java.awt.Dimension(240, 30));
        btnServeCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServeCustomersIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnManageProfile.setBackground(new java.awt.Color(102, 153, 255));
        btnManageProfile.setFont(getFont());
        btnManageProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnManageProfile.setText("Manage Profile");
        btnManageProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageProfile.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageProfile.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageProfile.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProfileActionPerformed(evt);
            }
        });

        btnReviewOSH.setBackground(new java.awt.Color(102, 153, 255));
        btnReviewOSH.setFont(getFont());
        btnReviewOSH.setForeground(new java.awt.Color(255, 255, 255));
        btnReviewOSH.setText("Review Order Status History");
        btnReviewOSH.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReviewOSH.setMaximumSize(new java.awt.Dimension(200, 40));
        btnReviewOSH.setMinimumSize(new java.awt.Dimension(20, 20));
        btnReviewOSH.setPreferredSize(new java.awt.Dimension(240, 25));
        btnReviewOSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewOSHActionPerformed(evt);
            }
        });

        btnReviewComission.setBackground(new java.awt.Color(102, 153, 255));
        btnReviewComission.setFont(getFont());
        btnReviewComission.setForeground(new java.awt.Color(255, 255, 255));
        btnReviewComission.setText("Review Comission");
        btnReviewComission.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReviewComission.setMaximumSize(new java.awt.Dimension(200, 40));
        btnReviewComission.setMinimumSize(new java.awt.Dimension(20, 20));
        btnReviewComission.setPreferredSize(new java.awt.Dimension(240, 25));
        btnReviewComission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewComissionActionPerformed(evt);
            }
        });

        btnPerformanceReports.setBackground(new java.awt.Color(102, 153, 255));
        btnPerformanceReports.setFont(getFont());
        btnPerformanceReports.setForeground(new java.awt.Color(255, 255, 255));
        btnPerformanceReports.setText("Performance Reports");
        btnPerformanceReports.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPerformanceReports.setMaximumSize(new java.awt.Dimension(200, 40));
        btnPerformanceReports.setMinimumSize(new java.awt.Dimension(20, 20));
        btnPerformanceReports.setPreferredSize(new java.awt.Dimension(240, 25));
        btnPerformanceReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerformanceReportsActionPerformed(evt);
            }
        });

        customerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameTextFieldActionPerformed(evt);
            }
        });

        lblCustomer.setText("Customer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnServeCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(btnManageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPerformanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReviewOSH, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addComponent(btnReviewComission, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(397, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnServeCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReviewOSH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReviewComission, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerformanceReports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(397, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnServeCustomersIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServeCustomersIdentifyResourceAssetsActionPerformed
        
// TODO add your handling code here:

 
        String customername = customerNameTextField.getText();
        if (customername.isEmpty()) return;
        CustomerProfile selectedCustomer = business.getCustomerDirectory().findCustomer(customername);

//        ProcessOrder aos = new ProcessOrder(business, selectedcustomer ,salesperson, workArea);
//
//        workArea.add("ManageVulns", aos);
//        ((java.awt.CardLayout) workArea.getLayout()).next(workArea);
        ProcessOrder panel = new ProcessOrder(workArea, business, selectedCustomer, salesPerson);
        workArea.add("ProcessOrder", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
        

    }//GEN-LAST:event_btnServeCustomersIdentifyResourceAssetsActionPerformed

    private void btnManageProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProfileActionPerformed
        // TODO add your handling code here:
        String customername = customerNameTextField.getText();
        if (customername.isEmpty()) return;
        CustomerProfile selectedCustomer = business.getCustomerDirectory().findCustomer(customername);
        ManageCustomerProfileJPanel panel = new ManageCustomerProfileJPanel(workArea, business, selectedCustomer, salesPerson);
        workArea.add("ManageCustomerProfileJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);

//        ManageVulns aos = new  ManageVulns(businessunit, CardSequencePanel);
        // aos.setAgenda(businessunit.getRiskManagementAgenda());
//        CardSequencePanel.add("ManageVulns", aos);
//        ((java.awt.CardLayout) workArea.getLayout()).next(workArea);

}//GEN-LAST:event_btnManageProfileActionPerformed

    private void btnReviewOSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewOSHActionPerformed
        // TODO add your handling code here:

//        ManageSalesPersonOrders iet = new ManageSalesPersonOrders(business, CardSequencePanel);
//
//        CardSequencePanel.add("FindResourceAsset", iet);
//        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        
        ManageSalesPersonOrders panel = new ManageSalesPersonOrders(workArea, business);
        workArea.add("ManageSalesPersonOrders", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);

    }//GEN-LAST:event_btnReviewOSHActionPerformed

    private void btnReviewComissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewComissionActionPerformed
        // TODO add your handling code here:

//        CardSequencePanel.removeAll();
        //      ViewBusinessUnitRiskProfile drpd= new ViewBusinessUnitRiskProfile(businessunit, CardSequencePanel);
//        ManageHazards drpd = new ManageHazards(businessunit, CardSequencePanel);
//        CardSequencePanel.add("ManageRiskProfiles", drpd);
//        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

        SalesPersonReviewComissionJPanel panel = new SalesPersonReviewComissionJPanel(workArea, business);
        workArea.add("SalesPersonReviewComissionJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
}//GEN-LAST:event_btnReviewComissionActionPerformed

    private void btnPerformanceReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerformanceReportsActionPerformed
        // TODO add your handling code here:

//        CardSequencePanel.removeAll();
//        ManageIncidents aos = new  ManageIncidents(businessunit, CardSequencePanel);
        // aos.setAgenda(businessunit.getRiskManagementAgenda());
//        CardSequencePanel.add("RiskAgendaObjectives", aos);
//        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        SalesPersonPerformanceReportJPanel panel = new SalesPersonPerformanceReportJPanel(workArea, business);
        workArea.add("SalesPersonPerformanceReportJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
          
}//GEN-LAST:event_btnPerformanceReportsActionPerformed

    private void customerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageProfile;
    private javax.swing.JButton btnPerformanceReports;
    private javax.swing.JButton btnReviewComission;
    private javax.swing.JButton btnReviewOSH;
    private javax.swing.JButton btnServeCustomers;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JLabel lblCustomer;
    // End of variables declaration//GEN-END:variables

}
