/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Education;

import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import business.Business;
import business.Education.Librarian;
import business.Education.Professor;
import business.Education.Student;
import business.Education.UniAdmin;
import business.Profiles.Profile;
import business.Role.Role;
import java.awt.CardLayout;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sanatpopli
 */
public class EducationLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EducationLoginJPanel
     */
    

    /**
     * Creates new form EducationLoginJPanel
     */
    JPanel workArea;
    Business business;
    public EducationLoginJPanel(JPanel workArea, Business business) {
        initComponents();
        this.workArea=workArea;
        this.business=business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRole = new javax.swing.JLabel();
        roleComboBox = new javax.swing.JComboBox<>();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));

        lblRole.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblRole.setText("Role");

        roleComboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Professor", "Student", "Librarian", "Admin" }));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUsername.setText("UserName");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPassword.setText("Password");

        btnLogin.setBackground(new java.awt.Color(255, 204, 204));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPassword)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(237, 237, 237)
                            .addComponent(lblRole))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(334, 334, 334)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addComponent(roleComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(271, 271, 271))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole)
                    .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addComponent(btnLogin)
                .addContainerGap(269, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            // TODO add your handling code here:
            
            String uname = txtUsername.getText();
            String password = txtPassword.getText();
            MessageDigest messageDigest =  MessageDigest.getInstance("SHA-256");
            byte[] md = messageDigest.digest(password.getBytes());
            BigInteger bigInt = new BigInteger(1, md);
            String hashedPassword = bigInt.toString(16);
            UserAccountDirectory uad = business.getUserAccountDirectory();
            UserAccount userAccount = uad.AuthenticateUser(uname, password);
            if(userAccount==null)
                return;
            Role r = userAccount.getRole();
            Profile profile = userAccount.getAssociatedPersonProfile();
            
            String selectedrole=(String) roleComboBox.getSelectedItem();
            
            if(profile instanceof Professor){
                if(selectedrole.equals("Professor")){
                ProfJPanel panel = new ProfJPanel(workArea, business);
                workArea.add("ProfJPanel", panel);
                CardLayout layout = (CardLayout) workArea.getLayout();
                layout.next(workArea);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Please check login credentials and Role again!", "Warning", JOptionPane.ERROR_MESSAGE);
                }
            }
            
            else if(profile instanceof Student){
                if(selectedrole.equals("Student")){
                    StudentJPanel panel = new StudentJPanel(workArea, business);
                    workArea.add("StudentJPanel", panel);
                    CardLayout layout = (CardLayout) workArea.getLayout();
                    layout.next(workArea);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Please check login credentials and Role again!", "Warning", JOptionPane.ERROR_MESSAGE);
                }
            }
            else if(profile instanceof Librarian){
                if(selectedrole.equals("Librarian")){
                    LibrarianJPanel panel = new LibrarianJPanel(workArea, business);
                    workArea.add("LibrarianJPanel", panel);
                    CardLayout layout = (CardLayout) workArea.getLayout();
                    layout.next(workArea);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Please check login credentials and Role again!", "Warning", JOptionPane.ERROR_MESSAGE);
                }
            }
            else if(profile instanceof UniAdmin){
                if(selectedrole.equals("UniAdmin")){
                    UniAdminJPanel panel = new UniAdminJPanel(workArea, business);
                    workArea.add("LibrarianJPanel", panel);
                    CardLayout layout = (CardLayout) workArea.getLayout();  
                    layout.next(workArea); 
                }
                else{
                    JOptionPane.showMessageDialog(null, "Please check login credentials and Role again!", "Warning", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(EducationLoginJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JComboBox<String> roleComboBox;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
