/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Education;

import business.Business;
import javax.swing.JPanel;

/**
 *
 * @author sanatpopli
 */
public class LibrarianJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LibrarianJPanel
     */
    

    /**
     * Creates new form LibrarianJPanel
     */
    JPanel workArea;
    Business business;
    public LibrarianJPanel(JPanel workArea, Business business) {
        initComponents();
        this.workArea=workArea;
        this.business=business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        txtHours = new javax.swing.JTextField();
        txtSchedule = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        txtTax = new javax.swing.JTextField();
        namejLabel = new javax.swing.JLabel();
        uidjLabel = new javax.swing.JLabel();
        txtUID = new javax.swing.JTextField();
        hoursjLabel = new javax.swing.JLabel();
        schedulejLabel = new javax.swing.JLabel();
        salaryjLabel = new javax.swing.JLabel();
        taxjLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        downloadjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        namejLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namejLabel.setText("Name");

        uidjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        uidjLabel.setText("UID");

        hoursjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hoursjLabel.setText("Hours/month");

        schedulejLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        schedulejLabel.setText("schedule");

        salaryjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salaryjLabel.setText("Salary");

        taxjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        taxjLabel.setText("Taxes");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Hey Librarian");

        downloadjButton.setBackground(new java.awt.Color(255, 204, 204));
        downloadjButton.setText("Download");
        downloadjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(downloadjButton)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(schedulejLabel)
                            .addComponent(salaryjLabel)
                            .addComponent(taxjLabel)
                            .addComponent(uidjLabel))
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHours, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSchedule)
                                .addComponent(txtSalary)
                                .addComponent(txtTax)
                                .addComponent(txtUID, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))))
                .addContainerGap(619, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(198, 198, 198)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(namejLabel)
                            .addGap(195, 195, 195)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(hoursjLabel))
                    .addContainerGap(617, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(txtHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(schedulejLabel))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salaryjLabel))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taxjLabel))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uidjLabel)
                    .addComponent(txtUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addComponent(downloadjButton)
                .addGap(28, 28, 28))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(namejLabel))
                    .addGap(54, 54, 54)
                    .addComponent(hoursjLabel)
                    .addContainerGap(463, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void downloadjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downloadjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton downloadjButton;
    private javax.swing.JLabel hoursjLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JLabel salaryjLabel;
    private javax.swing.JLabel schedulejLabel;
    private javax.swing.JLabel taxjLabel;
    private javax.swing.JTextField txtHours;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSchedule;
    private javax.swing.JTextField txtTax;
    private javax.swing.JTextField txtUID;
    private javax.swing.JLabel uidjLabel;
    // End of variables declaration//GEN-END:variables
}
