/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorWorkArea;

import Business.Doctor.MedicalAssistant;
import Business.Doctor.PrescriptionList;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DoctorWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nisha
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private DoctorOrganization org;
    private Enterprise ep;
    private UserAccount userAcc;
    private MedicalAssistant assistant;
    private PrescriptionList pL;
    private DoctorWorkRequest docreq;
    private Network network;
    private EcoSystem system;
    private static final String CLASS_NAME = DoctorWorkAreaJPanel.class.getName();

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount acc, DoctorOrganization docOrg, Enterprise enterprise, EcoSystem system, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAcc = acc;
        this.org = docOrg;
        this.ep = enterprise;
        this.network = network;
        this.system = system;
        network();
    }

    public void network() {
        network.getName();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrescription = new javax.swing.JButton();
        btnTestLab = new javax.swing.JButton();
        lblDoctor = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setPreferredSize(new java.awt.Dimension(2000, 1200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrescription.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnPrescription.setForeground(new java.awt.Color(0, 0, 255));
        btnPrescription.setText("WRITE PRESCRIPTION");
        btnPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrescriptionActionPerformed(evt);
            }
        });
        add(btnPrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 497, 83));

        btnTestLab.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnTestLab.setForeground(new java.awt.Color(51, 51, 255));
        btnTestLab.setText("Lab Test");
        btnTestLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestLabActionPerformed(evt);
            }
        });
        add(btnTestLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 510, 90));

        lblDoctor.setBackground(new java.awt.Color(0, 204, 204));
        lblDoctor.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblDoctor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoctor.setText("DOCTOR WORK AREA ");
        add(lblDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, 67));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrescriptionActionPerformed
        // TODO add your handling code here:

         CardLayout layout = (CardLayout) userProcessContainer.getLayout();
         userProcessContainer.add("DoctorPrescWorkAreaJPanel", new userinterface.DoctorWorkArea.DoctorPrescWorkAreaJPanel(userProcessContainer,pL,userAcc,ep,org,system,network));
         layout.next(userProcessContainer);

    }//GEN-LAST:event_btnPrescriptionActionPerformed

    private void btnTestLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestLabActionPerformed
        // TODO add your handling code here:

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("LabDocExaminationWorkAeaJPanel", new userinterface.DoctorWorkArea.RequestDocWorkAreaJPanel(userProcessContainer, userAcc, org, ep, system, network));

        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnTestLabActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrescription;
    private javax.swing.JButton btnTestLab;
    private javax.swing.JLabel lblDoctor;
    // End of variables declaration//GEN-END:variables
}
