/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorWorkArea;

import Business.Doctor.Prescription;
import Business.Doctor.PrescriptionList;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;

import Business.Organization.Organization;
import Business.Organization.PharmaOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DoctorWorkRequest;
import Business.WorkQueue.PharmaWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nisha
 */
public class DoctorPrescWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorPrescWorkAreaJPanel
     */
    private PrescriptionList pL;
    private DoctorOrganization org;
    private Enterprise ep;
    private UserAccount userAcc;
    private JPanel userProcessContainer;
    private Prescription p;
    private DoctorWorkRequest docreq;
    private Network network;
    private EcoSystem system;
    private static final String filePath = "./prescription data.txt";

    public DoctorPrescWorkAreaJPanel(JPanel userProcessContainer, PrescriptionList PList, UserAccount acc, Enterprise enterprise, DoctorOrganization docOrg, EcoSystem system, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAcc = acc;
        this.ep = enterprise;
        this.org = docOrg;
        this.network = network;
        this.system = system;
        
        tblPopulateWorkRequest();
        DateChooserBox.setMinSelectableDate(new Date());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDoctorPrescription = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtNameField = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        lblDiagnosis = new javax.swing.JLabel();
        lblMedication = new javax.swing.JLabel();
        diagnosisComboBox = new javax.swing.JComboBox<>();
        lblNoDoses = new javax.swing.JLabel();
        lblDuration = new javax.swing.JLabel();
        btnSavePrescription = new javax.swing.JButton();
        txtNoofDose = new javax.swing.JSpinner();
        txtNoofDays = new javax.swing.JSpinner();
        scrollPane2 = new javax.swing.JScrollPane();
        tblPrescription = new javax.swing.JTable();
        lblDate = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        DateChooserBox = new com.toedter.calendar.JDateChooser();
        medicationCombobox = new javax.swing.JComboBox<>();
        lblImg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 48)); // NOI18N
        setPreferredSize(new java.awt.Dimension(2000, 1200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDoctorPrescription.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblDoctorPrescription.setText("Doctor Prescription");
        add(lblDoctorPrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        lblName.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblName.setText("Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));
        add(txtNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 287, -1));

        lblAge.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblAge.setText("Age:");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 287, -1));

        lblGender.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblGender.setText("Gender:");
        add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        genderComboBox.setBackground(new java.awt.Color(255, 255, 153));
        genderComboBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Please select--", "Male", "Female" }));
        genderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboBoxActionPerformed(evt);
            }
        });
        add(genderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 287, -1));

        lblDiagnosis.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblDiagnosis.setText("Disease:");
        add(lblDiagnosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        lblMedication.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblMedication.setText("Medication:");
        add(lblMedication, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 424, -1, -1));

        diagnosisComboBox.setBackground(new java.awt.Color(255, 255, 153));
        diagnosisComboBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        diagnosisComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Please select--", "DiseaseCannbis ", "DiseaseFentanyl ", "DiseaseMDMA", "DiseaseSteroids", "DiseaseCocaine", "DiseaseHeroine", "DiseaseHallucinogens", "DiseaseLSD" }));
        diagnosisComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosisComboBoxActionPerformed(evt);
            }
        });
        add(diagnosisComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 287, 30));

        lblNoDoses.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblNoDoses.setText("No. of Doses");
        add(lblNoDoses, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 424, -1, -1));

        lblDuration.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblDuration.setText("Duration");
        add(lblDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(966, 424, -1, -1));

        btnSavePrescription.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSavePrescription.setText("SAVE  PRESCRIPTION");
        btnSavePrescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSavePrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePrescriptionActionPerformed(evt);
            }
        });
        add(btnSavePrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 500, 270, 40));

        txtNoofDose.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        add(txtNoofDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 429, 170, 31));

        txtNoofDays.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        add(txtNoofDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 420, 171, 30));

        tblPrescription.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tblPrescription.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Total Quantity", "Reciever"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPrescription.setRowHeight(25);
        scrollPane2.setViewportView(tblPrescription);

        add(scrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, 818, 173));

        lblDate.setBackground(new java.awt.Color(0, 0, 0));
        lblDate.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblDate.setText("Date: ");
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 79, -1));

        backBtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 0, 102));
        backBtn.setText("BACK");
        backBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 790, 70, -1));

        DateChooserBox.setBackground(new java.awt.Color(255, 255, 153));
        add(DateChooserBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 180, 32));

        medicationCombobox.setBackground(new java.awt.Color(255, 255, 153));
        medicationCombobox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        medicationCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Please select--", "Atorvastatin", "Levothyroxine", "Lisinopril", "Metformin", "Metoprolol", "Amlodipine", "Albuterol", "Omeprazole" }));
        medicationCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicationComboboxActionPerformed(evt);
            }
        });
        add(medicationCombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 426, 287, -1));

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/doc.png"))); // NOI18N
        add(lblImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -20, 1520, 970));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSavePrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePrescriptionActionPerformed
        // TODO add your handling code here:

        Prescription p = new Prescription();
        p.setDiagnoseOfDisease(diagnosisComboBox.getSelectedItem().toString());
        p.setMedicine(medicationCombobox.getSelectedItem().toString());

        p.setNumberOfDosesInDay((Integer) txtNoofDose.getValue());

        p.setNumberOfDays((Integer) txtNoofDays.getValue());
        p.setNetwork(network.getName());
        
        
        
        String age = txtAge.getText();
        boolean check = true;
        try {
            Integer.parseInt(age);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Age must be integer!");
            check = false;
            return;
        }

        if (p.getDiagnoseOfDisease().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the diagnosis!");
            check = false;
            return;
        } else if (txtNameField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the patient name!");
            check = false;
            return;

        }
         if(((Integer) txtNoofDose.getValue())==0|| ((Integer) txtNoofDays.getValue())==0)
                {
                     JOptionPane.showMessageDialog(null, "Please enter the no of dose in a day or duration !");
             check = false;
             return;
                }
         if(DateChooserBox.getDate()==null)
         {
             JOptionPane.showMessageDialog(null, "Choose the date!");
             check = false;
             return;
         }
         if(medicationCombobox.getSelectedIndex()<=0)
         {
             JOptionPane.showMessageDialog(null, "Please select the Medication Name !");
             check = false;
         }
         if(genderComboBox.getSelectedIndex()<=0)
         {
          JOptionPane.showMessageDialog(null, "Please select the Medication Name !");
             check = false;   
             return;
         }
         if(diagnosisComboBox.getSelectedIndex()<=0)
         {
             JOptionPane.showMessageDialog(null, "please select the diagonsis name");
             check=false;
             return;
         }
        
        if (check == true) {
            
            
            org.addPrescription(p);

            PharmaWorkRequest req = new PharmaWorkRequest();
            String mn = medicationCombobox.getSelectedItem().toString();
            int qty = ((Integer) txtNoofDose.getValue()) * ((Integer) txtNoofDays.getValue());
            req.setMedicationName(mn);
            req.setQuantity(qty);
            req.setSender(userAcc);
            req.setStatus("Sent");
            JOptionPane.showMessageDialog(null, "Prescription added successfully");

            Organization org = null;
            ArrayList<Enterprise> epList = network.getEnterpriseDirectory().getEnterpriseList();          
                for (Enterprise enterprise: epList) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof PharmaOrganization) {
                            org = organization;
                            break;
                        }
                    }
                }
            
            if (org != null) {

                org.getWorkQueue().getWorkRequestList().add(req);
                userAcc.getWorkQueue().getWorkRequestList().add(req);
            }
            
           

            tblPopulateWorkRequest();
            saveRecord(p.getNetwork(),p.getDiagnoseOfDisease(),p.getMedicine());
            txtNameField.setText("");
            txtAge.setText("");
             txtNoofDose.setValue(0);
             txtNoofDays.setValue(0);
             genderComboBox.setSelectedIndex(0);
             medicationCombobox.setSelectedIndex(0);
            
        }


    }//GEN-LAST:event_btnSavePrescriptionActionPerformed
    
    public void saveRecord(String network,String disease,String medicine){
        try {
            FileWriter file = new FileWriter(filePath,true);
            BufferedWriter bw = new BufferedWriter(file);
            PrintWriter pw = new PrintWriter(bw);
            pw.println(network+","+disease+","+medicine);
            pw.flush();
            pw.close();
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(DoctorPrescWorkAreaJPanel.class.getName()).log(Level.SEVERE, null, ex);
           
        }
        
    }
    
    private void diagnosisComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosisComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diagnosisComboBoxActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void genderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboBoxActionPerformed

    private void medicationComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicationComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicationComboboxActionPerformed


    public void tblPopulateWorkRequest() {

        DefaultTableModel model = (DefaultTableModel) tblPrescription.getModel();

        model.setRowCount(0);

        for (WorkRequest request : userAcc.getWorkQueue().getWorkRequestList()) {
            if (request instanceof PharmaWorkRequest) {
                Object[] row = new Object[4];

                String med = ((PharmaWorkRequest) request).getMedicationName();

                row[0] = (PharmaWorkRequest) request;
                int quantity = ((PharmaWorkRequest) request).getQuantity();
                row[1] = quantity;
                row[2] = request.getReceiver();
                String result = request.getStatus();
                row[3] = result == null ? "Waiting" : result;

                model.addRow(row);

            }
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooserBox;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnSavePrescription;
    private javax.swing.JComboBox<String> diagnosisComboBox;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDiagnosis;
    private javax.swing.JLabel lblDoctorPrescription;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblMedication;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNoDoses;
    private javax.swing.JComboBox<String> medicationCombobox;
    private javax.swing.JScrollPane scrollPane2;
    private javax.swing.JTable tblPrescription;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtNameField;
    private javax.swing.JSpinner txtNoofDays;
    private javax.swing.JSpinner txtNoofDose;
    // End of variables declaration//GEN-END:variables
}
