/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorWorkArea;

import Business.DrugCompounds.DrugCompounds;

import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nisha
 */
public class LabDocExaminationWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabDocExaminationWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private LabTestWorkRequest Testrequest;

    public LabDocExaminationWorkAreaJPanel(JPanel userProcessContainer, LabTestWorkRequest req) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.Testrequest = req;
        txtPatientfield.setText(req.getPatientName());
        tblPopulate();

    }

    public void tblPopulate() {
        DefaultTableModel dtm = (DefaultTableModel) tblDrug.getModel();

        dtm.setRowCount(0);

//        System.out.println(((LabTestWorkRequest) Testrequest).getPatient().getDrugHistory().getDrugCompoundHistory());
//        System.out.println(((LabTestWorkRequest) Testrequest).getPatient().getDrugHistory().getDrugCompoundHistory().size());
        LabTestWorkRequest Ltw = (LabTestWorkRequest) Testrequest;
        ArrayList<DrugCompounds> drugCompoundHistory = (Ltw).getPatient().getDrugHistory().getDrugCompoundHistory();
        for (DrugCompounds dc : drugCompoundHistory) {

            Object[] row = new Object[2];
            row[0] = dc.getId();
            row[1] = dc.getDrugCompound();
//            System.out.println(((LabTestWorkRequest) Testrequest).getPatient());

            dtm.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLabTest = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        tblDrug = new javax.swing.JTable();
        txtPatientfield = new javax.swing.JTextField();
        lblPatient = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setPreferredSize(new java.awt.Dimension(2000, 1200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLabTest.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblLabTest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLabTest.setText(" LAB TEST RESULTS");
        add(lblLabTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 490, 52));

        refreshBtn.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        refreshBtn.setText("REFRESH");
        refreshBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        add(refreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 600, 157, -1));

        tblDrug.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        tblDrug.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Drug"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDrug.setEnabled(false);
        tblDrug.setRowHeight(22);
        jScrollPane.setViewportView(tblDrug);

        add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, 200));

        txtPatientfield.setEditable(false);
        add(txtPatientfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 200, 30));

        lblPatient.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblPatient.setText("Patient Name :");
        add(lblPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 180, 30));

        backBtn.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        backBtn.setText(" Back");
        backBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/DrugLabResults.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_refreshBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        userProcessContainer.remove(this);
        Component[] cArray = userProcessContainer.getComponents();
        Component c = cArray[cArray.length - 1];
        RequestDocWorkAreaJPanel reqDWAP = (RequestDocWorkAreaJPanel) c;
        reqDWAP.tblPopulateRequest();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblLabTest;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTable tblDrug;
    private javax.swing.JTextField txtPatientfield;
    // End of variables declaration//GEN-END:variables
}
