/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorWorkArea;

import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author nisha
 */
public class LabTrailDocWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabTrailDocWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private LabTestWorkRequest Testrequest;
    private static final String CLASS_NAME = LabTrailDocWorkAreaJPanel.class.getName();
    public LabTrailDocWorkAreaJPanel(JPanel userProcessContainer, LabTestWorkRequest req) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.Testrequest = req;
        txtPatientField.setText(req.getPatientName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPatient = new javax.swing.JLabel();
        txtPatientField = new javax.swing.JTextField();
        LabTestLbl = new javax.swing.JLabel();
        GencomboBox = new javax.swing.JComboBox<>();
        lblStatus = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblImg1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPatient.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblPatient.setText("Patient Name :");
        add(lblPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 226, 180, 30));

        txtPatientField.setEditable(false);
        add(txtPatientField, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 226, 200, 30));

        LabTestLbl.setBackground(new java.awt.Color(0, 0, 0));
        LabTestLbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LabTestLbl.setText(" CLINICAL TRAIL STATUS");
        add(LabTestLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 34, 420, 52));

        GencomboBox.setBackground(new java.awt.Color(255, 255, 153));
        GencomboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GencomboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Please select--", "Success", "Failure" }));
        add(GencomboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 311, 200, -1));

        lblStatus.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblStatus.setText("Status:");
        add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 303, 180, 30));

        btnSubmit.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 405, 135, 41));

        btnBack.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnBack.setText("<< BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 140, 40));

        lblImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/clinical.jpg"))); // NOI18N
        add(lblImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
         
        String Status = GencomboBox.getSelectedItem().toString();
        
        if((Status =="") || (!Status.equalsIgnoreCase("--Please select--"))){
            
            Testrequest.getPatient().setClinicalProgressBar(Status);
            JOptionPane.showMessageDialog(null, "Status has been updated successfully");
    }
        
        else{
            JOptionPane.showMessageDialog(null, "Please select clincal Status");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        Component[] cArray = userProcessContainer.getComponents();
        Component c = cArray[cArray.length - 1];
        RequestDocWorkAreaJPanel reqDWAP = (RequestDocWorkAreaJPanel) c;
        reqDWAP.tblPopulateRequest();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> GencomboBox;
    private javax.swing.JLabel LabTestLbl;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblImg1;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtPatientField;
    // End of variables declaration//GEN-END:variables
}
