/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkArea.Faculty;

import Business.Business;
import Business.Course.Course;
import Business.Feedback.Feedback;
import Business.Profiles.ProfessorProfile;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class FacultyDashboardJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FacultyDashboardJPanel
     */
    

    /**
     * Creates new form FacultyDashboardJPanel
     */
    JPanel workArea;
    Business business;
    ProfessorProfile professorProfile;
    public FacultyDashboardJPanel(JPanel workArea, Business business, ProfessorProfile professorProfile) {
        initComponents();
        this.workArea=workArea;
        this.business=business;
        this.professorProfile = professorProfile;
        txtProfName.setText(professorProfile.getFirstName() + " " + professorProfile.getLastName());
        populateTable();
        populateEmpFdbk();
//        System.out.println(professorProfile.getFirstName());
    }
    
    public void populateEmpFdbk(){
        DefaultTableModel dtm = (DefaultTableModel) tblEmpFdbk.getModel();
        dtm.setRowCount(0);
        
        for(Feedback fb : professorProfile.getEmployerFeedbackList()){
            Object row []  = new Object[3];
//            System.out.println(fb.getEmployer());
            row[0] = fb;
//            System.out.println(fb.getEmployerFeedback());
            row[1] = fb.getEmployerFeedback();
            dtm.addRow(row);
        }
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblOngoingCourseTable.getModel();
        dtm.setRowCount(0);
        
        for(Course c : professorProfile.getCoursesOffered()){
            Object row[] = new Object[3];
            
            row[0] = c;
            row[1] = c.getOfferingTerm();
            
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFacultyDashboard = new javax.swing.JLabel();
        btnManageStudentProfile = new javax.swing.JButton();
        btnManageCourse = new javax.swing.JButton();
        btnPerformanceReport = new javax.swing.JButton();
        btnOngoingCourse = new javax.swing.JLabel();
        txtProfName = new javax.swing.JTextField();
        lblProfSalutation = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOngoingCourseTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEmpFdbk = new javax.swing.JTable();
        lblEmpFdbk = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));

        lblFacultyDashboard.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblFacultyDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFacultyDashboard.setText("Faculty Dashboard");

        btnManageStudentProfile.setBackground(new java.awt.Color(204, 255, 204));
        btnManageStudentProfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnManageStudentProfile.setText("Manage Student Profile ");
        btnManageStudentProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageStudentProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudentProfileActionPerformed(evt);
            }
        });

        btnManageCourse.setBackground(new java.awt.Color(204, 255, 204));
        btnManageCourse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnManageCourse.setText("Manage Course");
        btnManageCourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCourseActionPerformed(evt);
            }
        });

        btnPerformanceReport.setBackground(new java.awt.Color(204, 255, 204));
        btnPerformanceReport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPerformanceReport.setText("Performance Report");
        btnPerformanceReport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPerformanceReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerformanceReportActionPerformed(evt);
            }
        });

        btnOngoingCourse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOngoingCourse.setText("Ongoing Course");
        btnOngoingCourse.setBorder(new javax.swing.border.MatteBorder(null));

        txtProfName.setEnabled(false);
        txtProfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfNameActionPerformed(evt);
            }
        });

        lblProfSalutation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProfSalutation.setText("Hi, Professor");

        tblOngoingCourseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Course", "Term"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblOngoingCourseTable);

        tblEmpFdbk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Employer ", "Feedback"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblEmpFdbk);

        lblEmpFdbk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmpFdbk.setText("Employer Feedback");
        lblEmpFdbk.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(lblProfSalutation, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProfName, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 746, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFacultyDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmpFdbk)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                        .addComponent(btnOngoingCourse, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnManageStudentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btnManageCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPerformanceReport, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(175, 175, 175))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnManageCourse, btnManageStudentProfile, btnPerformanceReport});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblFacultyDashboard)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfSalutation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btnOngoingCourse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblEmpFdbk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnManageCourse)
                            .addComponent(btnManageStudentProfile))
                        .addGap(59, 59, 59)
                        .addComponent(btnPerformanceReport)))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnManageCourse, btnManageStudentProfile, btnPerformanceReport});

    }// </editor-fold>//GEN-END:initComponents

    private void btnManageStudentProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudentProfileActionPerformed
        // TODO add your handling code here:
        ManageStudentProfileJPanel panel=new ManageStudentProfileJPanel(workArea,business,professorProfile);
        workArea.add("ManageStudentProfileJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnManageStudentProfileActionPerformed

    private void btnManageCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCourseActionPerformed
        // TODO add your handling code here:
        ManageCourseJPanel panel=new ManageCourseJPanel(workArea,business,professorProfile);
        workArea.add("ManageCourseJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
        
    }//GEN-LAST:event_btnManageCourseActionPerformed

    private void btnPerformanceReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerformanceReportActionPerformed
        // TODO add your handling code here:
        PerformanceReportJPanel panel=new PerformanceReportJPanel(workArea,business, professorProfile);
        workArea.add("ManageCourseJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
        
    }//GEN-LAST:event_btnPerformanceReportActionPerformed

    private void txtProfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCourse;
    private javax.swing.JButton btnManageStudentProfile;
    private javax.swing.JLabel btnOngoingCourse;
    private javax.swing.JButton btnPerformanceReport;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblEmpFdbk;
    private javax.swing.JLabel lblFacultyDashboard;
    private javax.swing.JLabel lblProfSalutation;
    private javax.swing.JTable tblEmpFdbk;
    private javax.swing.JTable tblOngoingCourseTable;
    private javax.swing.JTextField txtProfName;
    // End of variables declaration//GEN-END:variables
}
