/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkArea.Student;

import Business.Business;
import Business.Profiles.StudentProfile;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class StudentGradAuthorityJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentGradAuthorityJPanel
     */
    

    /**
     * Creates new form StudentGradAuthorityJPanel
     */
    JPanel workArea;
    Business business;
    StudentProfile studentProfile;
    public StudentGradAuthorityJPanel(JPanel workArea, Business business, StudentProfile studentProfile) {
        initComponents();
        this.workArea=workArea;
        this.business=business;
        this.studentProfile = studentProfile;
        
        if(studentProfile.getRequestStatus().equals("In progess")){
            lblAuditRequested.setVisible(true);
            btnRequestAudit.setEnabled(false);
            txtAuditResult.append("Your case is being reviewed by the Graduation Authority department!");
        }
        if(studentProfile.getRequestStatus().equals("Not sent")){
            lblAuditRequested.setVisible(false);
            btnRequestAudit.setEnabled(true);
            txtAuditResult.append("Request for Graduation Audit has not been yet sent!");
        }
        
        if(studentProfile.getRequestStatus().equals("Completed")){
            lblAuditRequested.setVisible(false);
            btnRequestAudit.setEnabled(false);
            if(studentProfile.isIsGraduated()==true){
                txtAuditResult.append("Congratulations! Your request for graduation has been Approved.");
            }
            if(studentProfile.getRequestStatus().equals("Completed")){
                if(studentProfile.isIsGraduated()==false)
                     txtAuditResult.append("We regret to inform you that your request has been denied by the GCA.");
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGradAuthority = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnRequestAudit = new javax.swing.JButton();
        lblAuditRequested = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAuditResult = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));

        lblGradAuthority.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblGradAuthority.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGradAuthority.setText("Student Graduation Request Work Area");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Raise a request for Graduation Audit by clicking this button  --->");

        btnRequestAudit.setBackground(new java.awt.Color(204, 255, 204));
        btnRequestAudit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRequestAudit.setText("REQUEST AUDIT");
        btnRequestAudit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestAuditActionPerformed(evt);
            }
        });

        lblAuditRequested.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAuditRequested.setText("Audit already requested!");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Audit Results ----->");

        txtAuditResult.setColumns(20);
        txtAuditResult.setRows(5);
        jScrollPane1.setViewportView(txtAuditResult);

        btnBack.setBackground(new java.awt.Color(204, 255, 204));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGradAuthority, javax.swing.GroupLayout.DEFAULT_SIZE, 967, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblAuditRequested, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRequestAudit, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(600, 600, 600))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblGradAuthority)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnRequestAudit))
                .addGap(18, 18, 18)
                .addComponent(lblAuditRequested)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(89, 89, 89))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestAuditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestAuditActionPerformed
        // TODO add your handling code here:
        studentProfile.setRequestStatus("In Progress");
        JOptionPane.showMessageDialog(null, "Your request has been sent to the GCA team!");
    }//GEN-LAST:event_btnRequestAuditActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    workArea.remove(this);
    Component[] componentArray = workArea.getComponents();
    Component component = componentArray[componentArray.length - 1];
    StudentPortalJPanel panel = (StudentPortalJPanel) component;
    CardLayout layout = (CardLayout) workArea.getLayout();
    layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestAudit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAuditRequested;
    private javax.swing.JLabel lblGradAuthority;
    private javax.swing.JTextArea txtAuditResult;
    // End of variables declaration//GEN-END:variables
}
