/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkArea.Student;

import Business.Business;
import Business.Course.Course;
import Business.Profiles.ProfessorProfile;
import Business.Profiles.StudentProfile;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class StudentCourseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentCourseJPanel
     */
   

    /**
     * Creates new form StudentCourseJPanel
     */
    JPanel workArea;
    Business business;
    StudentProfile studentProfile;
    public StudentCourseJPanel(JPanel workArea, Business business, StudentProfile studentProfile) {
        initComponents();
        this.workArea=workArea;
        this.business=business;
        this.studentProfile = studentProfile;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblStudentRegisteredCourses.getModel();
        model.setRowCount(0);
        
        for(Course c : studentProfile.getCoursesTaken()){
            Object[] row = new Object[5];
            row[0] = c;
            row[1] = c.getCourseId();
            row[2] = c.getProfName();
            row[3] = c.getCredits();
            row[4] = c.getProfRating();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCourseList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudentRegisteredCourses = new javax.swing.JTable();
        btnRegisterMoreCourse = new javax.swing.JButton();
        btnDrop = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnViewCourse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtAddRatings = new javax.swing.JTextField();
        btnSubmitRating = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));

        lblCourseList.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblCourseList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCourseList.setText("My Registered Courses ");

        tblStudentRegisteredCourses.setBackground(new java.awt.Color(204, 204, 204));
        tblStudentRegisteredCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course ", "Course Id", "Professor ", "Credits", "Professor Rating"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblStudentRegisteredCourses);

        btnRegisterMoreCourse.setBackground(new java.awt.Color(204, 255, 204));
        btnRegisterMoreCourse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegisterMoreCourse.setText("Register Other Course");
        btnRegisterMoreCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterMoreCourseActionPerformed(evt);
            }
        });

        btnDrop.setBackground(new java.awt.Color(204, 255, 204));
        btnDrop.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDrop.setText("Drop");
        btnDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(204, 255, 204));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnViewCourse.setBackground(new java.awt.Color(204, 255, 204));
        btnViewCourse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnViewCourse.setText("View Course");
        btnViewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCourseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Select course and add rating for professor ->");

        txtAddRatings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddRatingsActionPerformed(evt);
            }
        });

        btnSubmitRating.setBackground(new java.awt.Color(204, 255, 204));
        btnSubmitRating.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSubmitRating.setText("Submit Rating");
        btnSubmitRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRatingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCourseList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDrop)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(btnViewCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(86, 86, 86)
                        .addComponent(btnRegisterMoreCourse))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAddRatings, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSubmitRating)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBack, btnDrop, btnRegisterMoreCourse, btnViewCourse});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblCourseList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDrop)
                    .addComponent(btnRegisterMoreCourse)
                    .addComponent(btnViewCourse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAddRatings, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmitRating)
                    .addComponent(btnBack))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBack, btnDrop, btnRegisterMoreCourse});

    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    workArea.remove(this);
    Component[] componentArray = workArea.getComponents();
    Component component = componentArray[componentArray.length - 1];
    CardLayout layout = (CardLayout) workArea.getLayout();
    layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropActionPerformed
        // TODO add your handling code here:
        int rowSelect = tblStudentRegisteredCourses.getSelectedRow();
        if(rowSelect < 0){
            JOptionPane.showMessageDialog(null, "Please select a course first!");
        }else{
            Course course = (Course) tblStudentRegisteredCourses.getValueAt(rowSelect,0);
            ArrayList<ProfessorProfile> professorList = business.getProfessorDirectory().getProfessorList();
            ArrayList<StudentProfile> studentList = business.getStudentDirectory().getStudentList();
            for(StudentProfile sp : studentList){
                if(sp.getNuid().equals(studentProfile.getNuid())){
                    sp.getCoursesTaken().remove(course);
                }
            }
            
            populateTable();
            JOptionPane.showMessageDialog(null, "Course dropped!");
        }
    }//GEN-LAST:event_btnDropActionPerformed

    private void btnRegisterMoreCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterMoreCourseActionPerformed
        // TODO add your handling code here:
        StudentCourseRegistrationJPanel panel = new StudentCourseRegistrationJPanel(workArea, business, studentProfile);
        workArea.add("StudentCourseRegistrationJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
        
    }//GEN-LAST:event_btnRegisterMoreCourseActionPerformed

    private void btnViewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCourseActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblStudentRegisteredCourses.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(null, "Please select a course to view!");
        }else{
            DefaultTableModel model = (DefaultTableModel) tblStudentRegisteredCourses.getModel();
            Course selectedCourse = (Course) model.getValueAt(selectedRowIndex, 0);
            ViewSelectedAvailableCourseDetailJPanel panel = new ViewSelectedAvailableCourseDetailJPanel(workArea, business, selectedCourse, studentProfile);
            workArea.add("ViewSelectedAvailableCourseDetailJPanel", panel);
            CardLayout layout = (CardLayout) workArea.getLayout();
            layout.next(workArea);
        }
    }//GEN-LAST:event_btnViewCourseActionPerformed

    private void txtAddRatingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddRatingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddRatingsActionPerformed

    private void btnSubmitRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRatingActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblStudentRegisteredCourses.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a course to give rating to the professor!");
            return;
        }else{
            DefaultTableModel model = (DefaultTableModel) tblStudentRegisteredCourses.getModel();
            Course selectedCourse = (Course) model.getValueAt(selectedRowIndex, 0);
            
            Double rating = Double.parseDouble(txtAddRatings.getText());
            selectedCourse.getProfRatingsList().add(rating);
            JOptionPane.showMessageDialog(null, "Added rating for professor "+ selectedCourse.getProfName());
            Double sum=0.0;
            for(Double d : selectedCourse.getProfRatingsList()){
                sum+=d;
            }
            selectedCourse.setProfRating(((sum)/(selectedCourse.getProfRatingsList().size())));
            txtAddRatings.setText("");
            populateTable();
        }
        
        
        
    }//GEN-LAST:event_btnSubmitRatingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDrop;
    private javax.swing.JButton btnRegisterMoreCourse;
    private javax.swing.JButton btnSubmitRating;
    private javax.swing.JButton btnViewCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourseList;
    private javax.swing.JTable tblStudentRegisteredCourses;
    private javax.swing.JTextField txtAddRatings;
    // End of variables declaration//GEN-END:variables
}
