/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkArea.GraduateCertificationAuthority;

import Business.Business;
import Business.Course.Course;
import Business.Course.CourseGrading;
import Business.Profiles.StudentProfile;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Bhagya
 */
public class GCARequestWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GCARequestWorkAreaJPanel
     */
    JPanel workArea;
    Business business;
    StudentProfile studentProfile;
    public GCARequestWorkAreaJPanel(JPanel workArea, Business business, StudentProfile studentProfile) {
        initComponents();
        this.workArea = workArea;
        this.business = business;
        this.studentProfile = studentProfile;
        populateTranscript();
        System.out.println("Trans.");
        Double a = calculateGPA();
        txtGpa.setText(String.format("%.2f",a));
        
    }
    
    public Double calculateGPA(){
        Double finalGPA=0.0;
        int count=0;
        for(Course c : studentProfile.getCoursesTaken()){
            for(CourseGrading cg : c.getCourseGradeList()){
                if(studentProfile.getNuid().equals(cg.getStudentId())){
                    finalGPA+= cg.getGpa();
                    count++;
                } 
            }
            
        }
        return (finalGPA/count);
    }
    public void populateTranscript(){
        ArrayList<Course> coursesTaken = studentProfile.getCoursesTaken();
        int lengthOfCourses = coursesTaken.size();
        int i=0;
        ArrayList<String> courseNames = new ArrayList<>();
        String cName="";
        for(i=0;i<coursesTaken.size();i++){
            cName =coursesTaken.get(i).getCourseName();
            courseNames.add(cName);
            cName="";
        }
//        while(i<lengthOfCourses){
//            String cName = coursesTaken.get(i).getCourseName();
//            courseNames.add(cName);
//            i++;
//        }
        int k = (8-lengthOfCourses);
        while(k>0){
            courseNames.add("Course not available");
            k--;
        }
        txtCourse1.setText(courseNames.get(0));
        txtCourse2.setText(courseNames.get(1));
        txtCourse3.setText(courseNames.get(2));
        txtCourse4.setText(courseNames.get(3));
        txtCourse5.setText(courseNames.get(4));
        txtCourse6.setText(courseNames.get(5));
        txtCourse7.setText(courseNames.get(6));
        txtCourse8.setText(courseNames.get(7));
//        
//        
        ArrayList<String> gradesList = new ArrayList<>();
        for(Course c : coursesTaken){
            for(CourseGrading cg : c.getCourseGradeList()){
                if(studentProfile.getNuid().equals(cg.getStudentId()))
                gradesList.add(cg.getFinalGrade());
            }
        }
        
        int lengthOfGradesList = gradesList.size();
        
        int len = 8-lengthOfGradesList; 
        while(len>0){
            gradesList.add("Grade not available!");
            len--;
        }
        txtGrade1.setText(gradesList.get(0));
        txtGrade2.setText(gradesList.get(1));
        txtGrade3.setText(gradesList.get(2));
        txtGrade4.setText(gradesList.get(3));
        txtGrade5.setText(gradesList.get(4));
        txtGrade6.setText(gradesList.get(5));
        txtGrade7.setText(gradesList.get(6));
        txtGrade8.setText(gradesList.get(7));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtGrade3 = new javax.swing.JTextField();
        lblGPA = new javax.swing.JLabel();
        txtGrade6 = new javax.swing.JTextField();
        lblGrades = new javax.swing.JLabel();
        txtCourse8 = new javax.swing.JTextField();
        lblCourse = new javax.swing.JLabel();
        txtCourse7 = new javax.swing.JTextField();
        txtCourse6 = new javax.swing.JTextField();
        txtCourse5 = new javax.swing.JTextField();
        txtGrade7 = new javax.swing.JTextField();
        txtGrade8 = new javax.swing.JTextField();
        txtCourse4 = new javax.swing.JTextField();
        txtGrade1 = new javax.swing.JTextField();
        txtCourse3 = new javax.swing.JTextField();
        txtGrade2 = new javax.swing.JTextField();
        txtCourse2 = new javax.swing.JTextField();
        txtCredits = new javax.swing.JTextField();
        txtCourse1 = new javax.swing.JTextField();
        txtGrade4 = new javax.swing.JTextField();
        txtGpa = new javax.swing.JTextField();
        lblTotCredit = new javax.swing.JLabel();
        txtGrade5 = new javax.swing.JTextField();
        btnCalculateEligibility = new javax.swing.JButton();
        txtCanGraduateRequest = new javax.swing.JTextField();
        btnApprove = new javax.swing.JButton();
        btnDeny = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Graduation Certification Authority Request Work Area ");

        txtGrade3.setEnabled(false);

        lblGPA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGPA.setText("GPA : ");

        txtGrade6.setEnabled(false);

        lblGrades.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGrades.setText("Grades : ");

        txtCourse8.setEnabled(false);

        lblCourse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCourse.setText("Courses: ");

        txtCourse7.setEnabled(false);

        txtCourse6.setEnabled(false);

        txtCourse5.setEnabled(false);

        txtGrade7.setEnabled(false);

        txtGrade8.setEnabled(false);

        txtCourse4.setEnabled(false);

        txtGrade1.setEnabled(false);

        txtCourse3.setEnabled(false);

        txtGrade2.setEnabled(false);

        txtCourse2.setEnabled(false);

        txtCredits.setEnabled(false);

        txtCourse1.setEnabled(false);

        txtGrade4.setEnabled(false);

        txtGpa.setEnabled(false);
        txtGpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGpaActionPerformed(evt);
            }
        });

        lblTotCredit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotCredit.setText("Total Credits Taken :");

        txtGrade5.setEnabled(false);

        btnCalculateEligibility.setBackground(new java.awt.Color(102, 102, 255));
        btnCalculateEligibility.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCalculateEligibility.setText("Calculate Eligibility");
        btnCalculateEligibility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateEligibilityActionPerformed(evt);
            }
        });

        txtCanGraduateRequest.setEnabled(false);

        btnApprove.setBackground(new java.awt.Color(102, 255, 102));
        btnApprove.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnDeny.setBackground(new java.awt.Color(255, 51, 51));
        btnDeny.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDeny.setText("Reject");
        btnDeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDenyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCourse7)
                        .addComponent(lblCourse)
                        .addComponent(txtCourse1)
                        .addComponent(txtCourse2)
                        .addComponent(txtCourse3)
                        .addComponent(txtCourse4)
                        .addComponent(txtCourse5)
                        .addComponent(txtCourse6)
                        .addComponent(txtCourse8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCalculateEligibility))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGrade7)
                    .addComponent(txtGrade1)
                    .addComponent(txtGrade2)
                    .addComponent(txtGrade3)
                    .addComponent(txtGrade4)
                    .addComponent(txtGrade5)
                    .addComponent(txtGrade6)
                    .addComponent(txtGrade8, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(lblGrades, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(txtCanGraduateRequest))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotCredit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGPA, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGpa, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeny)
                    .addComponent(btnApprove))
                .addGap(270, 270, 270))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnApprove, btnCalculateEligibility, btnDeny});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCourse)
                            .addComponent(lblGrades))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCourse2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCourse3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCourse4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCourse5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCourse6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCourse7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCourse8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(txtGrade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtGrade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGPA)
                                    .addComponent(txtGpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTotCredit)
                                    .addComponent(txtCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGrade3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGrade4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGrade5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGrade6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGrade7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGrade8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70)
                .addComponent(btnApprove)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculateEligibility)
                    .addComponent(txtCanGraduateRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeny)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnApprove, btnCalculateEligibility, btnDeny});

    }// </editor-fold>//GEN-END:initComponents

    private void txtGpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGpaActionPerformed

    private void btnCalculateEligibilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateEligibilityActionPerformed
        // TODO add your handling code here:
        boolean canGraduate = true;
        ArrayList<Course> coursesTaken = studentProfile.getCoursesTaken();
        if(!(coursesTaken.size()>7)){
            canGraduate = false;
        }
        for(Course c : coursesTaken){
            for(CourseGrading cg : c.getCourseGradeList()){
                if(studentProfile.getNuid().equals(cg.getStudentId())){
                    String finalGrade = cg.getFinalGrade();
//                    System.err.println("Checking F");
                    if(finalGrade.equals("F"))
                         canGraduate = false;
                }
            }
            
        }
        System.out.println(canGraduate);
        if(canGraduate == true){
            txtCanGraduateRequest.setText("Approve");
        }
        else{
            txtCanGraduateRequest.setText("Reject");
        }
        
        JOptionPane.showMessageDialog(null, "Eligibility has been calculated. Please press the approve or reject button as per the text box.");
        
    }//GEN-LAST:event_btnCalculateEligibilityActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        studentProfile.setIsGraduated(true);
        studentProfile.setRequestStatus("Completed");
        JOptionPane.showMessageDialog(null, "Student "+ studentProfile.getFirstName() + " " + studentProfile.getLastName() + " graduation request has been ACCEPTED!");
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnDenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDenyActionPerformed
        // TODO add your handling code here:
         studentProfile.setIsGraduated(false);
        studentProfile.setRequestStatus("Completed");
        JOptionPane.showMessageDialog(null, "Student "+ studentProfile.getFirstName() + " " + studentProfile.getLastName() + " graduation request has been REJECTED!");
    }//GEN-LAST:event_btnDenyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnCalculateEligibility;
    private javax.swing.JButton btnDeny;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblGPA;
    private javax.swing.JLabel lblGrades;
    private javax.swing.JLabel lblTotCredit;
    private javax.swing.JTextField txtCanGraduateRequest;
    private javax.swing.JTextField txtCourse1;
    private javax.swing.JTextField txtCourse2;
    private javax.swing.JTextField txtCourse3;
    private javax.swing.JTextField txtCourse4;
    private javax.swing.JTextField txtCourse5;
    private javax.swing.JTextField txtCourse6;
    private javax.swing.JTextField txtCourse7;
    private javax.swing.JTextField txtCourse8;
    private javax.swing.JTextField txtCredits;
    private javax.swing.JTextField txtGpa;
    private javax.swing.JTextField txtGrade1;
    private javax.swing.JTextField txtGrade2;
    private javax.swing.JTextField txtGrade3;
    private javax.swing.JTextField txtGrade4;
    private javax.swing.JTextField txtGrade5;
    private javax.swing.JTextField txtGrade6;
    private javax.swing.JTextField txtGrade7;
    private javax.swing.JTextField txtGrade8;
    // End of variables declaration//GEN-END:variables
}
