    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author sohni
 */
public class AdminSystemWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminSystemWorkAreaJPanel
     */
    JPanel workArea;
    EcoSystem business;
    
    public AdminSystemWorkAreaJPanel(JPanel workArea,EcoSystem business) {
        initComponents();
        this.workArea=workArea;
        this.business=business;
        tblPopulateData();
    }
    
    public void tblPopulateData(){
        DefaultTreeModel mod=(DefaultTreeModel)jTree.getModel();
        ArrayList<Network> nL=business.getNetworkList();
        ArrayList<Enterprise> eL;
        ArrayList<Organization> oL;
        
        Network nw;
        Enterprise ep;
        Organization org;
        
        DefaultMutableTreeNode nws=new DefaultMutableTreeNode("Networks");
        DefaultMutableTreeNode rootnode=(DefaultMutableTreeNode)mod.getRoot();
        rootnode.removeAllChildren();
        rootnode.insert(nws, 0);
        
        DefaultMutableTreeNode nwN;
        DefaultMutableTreeNode epN;
        DefaultMutableTreeNode ogN;
        
        for(int p=0;p<nL.size();p++){
            nw=nL.get(p);
            nwN=new DefaultMutableTreeNode(nw.getName());
            nws.insert(nwN, p);
            
            eL=nw.getEnterpriseDirectory().getEnterpriseList();
            for(int q=0; q<eL.size();q++){
                ep=eL.get(q);
                epN=new DefaultMutableTreeNode(ep.getName());
                nwN.insert(epN, q);
                
                oL=ep.getOrganizationDirectory().getOrganizationList();
                for(int r=0;r<oL.size();r++){
                    org=oL.get(r);
                    ogN=new DefaultMutableTreeNode(org.getName());
                    epN.insert(ogN, r);
                }
            }
        }
        mod.reload();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblSelectedNode = new javax.swing.JLabel();
        btnManageNetwork = new javax.swing.JButton();
        btnManageEnterprise = new javax.swing.JButton();
        btnManageAdmin = new javax.swing.JButton();
        btnViewReports = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 322, Short.MAX_VALUE))
        );

        jSplitPane.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Select node:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        lblSelectedNode.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblSelectedNode.setText("<View_selected_node>");
        jPanel2.add(lblSelectedNode, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        btnManageNetwork.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnManageNetwork.setText("Manage Network");
        btnManageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetworkActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 99, 390, -1));

        btnManageEnterprise.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnManageEnterprise.setText("Manage Enterprise");
        btnManageEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterpriseActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 146, 390, -1));

        btnManageAdmin.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnManageAdmin.setText("Manage Enterprise Admin");
        btnManageAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAdminActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 193, 390, -1));

        btnViewReports.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnViewReports.setText("View Reports");
        btnViewReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReportsActionPerformed(evt);
            }
        });
        jPanel2.add(btnViewReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 390, 40));

        jSplitPane.setRightComponent(jPanel2);

        add(jSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetworkActionPerformed
        NetworkManagementJPanel panel=new NetworkManagementJPanel(workArea, business);
        workArea.add("NetworkManagementJPanel",panel);
        CardLayout layout=(CardLayout)workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnManageNetworkActionPerformed

    private void btnManageEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterpriseActionPerformed
      if(business.getNetworkList().size()<=0)
      {
          JOptionPane.showMessageDialog(null,"No network available to create a enterprise");
          return;
                  }
      else
      {
        EnterpriseManagementJPanel panel=new EnterpriseManagementJPanel(workArea, business);
        workArea.add("EnterpriseManagementJPanel",panel);
        CardLayout layout=(CardLayout)workArea.getLayout();
        layout.next(workArea);
      }
    }//GEN-LAST:event_btnManageEnterpriseActionPerformed

    private void btnManageAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAdminActionPerformed
        int i =0;
        for(Network n:business.getNetworkList() )
        {
            for(Enterprise e :n.getEnterpriseDirectory().getEnterpriseList())
            {
                i++;
                
            }
        }
        if(i<=0)
        {
            JOptionPane.showMessageDialog(null,"No enterprise is available at a moment to create a admin for the enterprise");
            return;
        }
        EnterpriseManagementAdminJPanel panel=new EnterpriseManagementAdminJPanel(workArea, business);
        workArea.add("EnterpriseManagementAdminJPanel",panel);
        CardLayout layout=(CardLayout)workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnManageAdminActionPerformed

    private void jTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeValueChanged
        
        DefaultMutableTreeNode sN= (DefaultMutableTreeNode)jTree.getLastSelectedPathComponent();
        if(sN!=null){
            lblSelectedNode.setText(sN.toString());
        }
    }//GEN-LAST:event_jTreeValueChanged

    private void btnViewReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReportsActionPerformed
        userinterface.SystemAdminWorkArea.ReportsJPanel ViewReports = new userinterface.SystemAdminWorkArea.ReportsJPanel(workArea, business);
        workArea.add("ViewReports",ViewReports);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
        
    }//GEN-LAST:event_btnViewReportsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageAdmin;
    private javax.swing.JButton btnManageEnterprise;
    private javax.swing.JButton btnManageNetwork;
    private javax.swing.JButton btnViewReports;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JTree jTree;
    private javax.swing.JLabel lblSelectedNode;
    // End of variables declaration//GEN-END:variables
}
