/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Role.AdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sohni
 */
public class EnterpriseManagementAdminJPanel extends javax.swing.JPanel {

    private JPanel workArea;
    private EcoSystem business;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public EnterpriseManagementAdminJPanel(JPanel workArea, EcoSystem business) {
        initComponents();

        this.workArea = workArea;
        this.business = business;

        tblPopulate();
        populateComboBox();
    }

    private void tblPopulate() {
        DefaultTableModel mod = (DefaultTableModel) enterprisesJTab.getModel();

        mod.setRowCount(0);
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    Object[] row = new Object[3];
                    row[0] = enterprise.getName();
                    row[1] = network.getName();
                    row[2] = userAccount.getUsername();

                    mod.addRow(row);
                }
            }
        }
    }

    private void populateComboBox(){
        networkComboBox.removeAllItems();
        
        for (Network network : business.getNetworkList()){
            networkComboBox.addItem(network);
        }
    }
    
    private void populateEnterpriseComboBox(Network network){
        enterpriseComboBox.removeAllItems();
        
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            enterpriseComboBox.addItem(enterprise);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterprisesJTab = new javax.swing.JTable();
        lblNetwork = new javax.swing.JLabel();
        networkComboBox = new javax.swing.JComboBox();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblEnterprise = new javax.swing.JLabel();
        enterpriseComboBox = new javax.swing.JComboBox();
        btnSubmit = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        passwordJPasswordField = new javax.swing.JPasswordField();
        backJButton = new javax.swing.JButton();
        lblEnterPriseAdmin = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setForeground(new java.awt.Color(0, 0, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterprisesJTab.setBackground(new java.awt.Color(255, 255, 153));
        enterprisesJTab.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        enterprisesJTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Network", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enterprisesJTab.setRowHeight(25);
        jScrollPane1.setViewportView(enterprisesJTab);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 690, 210));

        lblNetwork.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblNetwork.setText("Network");
        add(lblNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        networkComboBox.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        networkComboBox.setForeground(new java.awt.Color(0, 0, 102));
        networkComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkComboBoxActionPerformed(evt);
            }
        });
        add(networkComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 220, -1));

        lblUserName.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblUserName.setText("UserName");
        add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, -1, 20));

        txtUserName.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(0, 0, 102));
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 220, -1));

        lblEnterprise.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblEnterprise.setText("Enterprises");
        add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, -1));

        enterpriseComboBox.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        enterpriseComboBox.setForeground(new java.awt.Color(0, 0, 102));
        enterpriseComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(enterpriseComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 220, -1));

        btnSubmit.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 670, -1, -1));

        lblPassword.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 0, 102));
        lblPassword.setText("Passcode");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, -1, -1));

        txtName.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 0, 102));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 580, 220, -1));

        lblName.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 102));
        lblName.setText("Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, -1, -1));

        passwordJPasswordField.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        passwordJPasswordField.setForeground(new java.awt.Color(0, 0, 102));
        add(passwordJPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 220, -1));

        backJButton.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        backJButton.setForeground(new java.awt.Color(0, 0, 102));
        backJButton.setText(" Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, -1, -1));

        lblEnterPriseAdmin.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lblEnterPriseAdmin.setText("Enterprise Head");
        add(lblEnterPriseAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 440, 52));
    }// </editor-fold>//GEN-END:initComponents

    private void networkComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkComboBoxActionPerformed

        Network network = (Network) networkComboBox.getSelectedItem();
        if (network != null){
            populateEnterpriseComboBox(network);
        }
        
        
    }//GEN-LAST:event_networkComboBoxActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if( txtUserName.getText().isEmpty()||txtName.getText().isEmpty()||passwordJPasswordField.getPassword().length<=0)
        {
            JOptionPane.showMessageDialog(null, "please enter all the imporant details");
            return;
        }
        
         Network nw = (Network) networkComboBox.getSelectedItem();
        Enterprise ep = (Enterprise) enterpriseComboBox.getSelectedItem();
        
        String user = txtUserName.getText().trim();
        String passcode = String.valueOf(passwordJPasswordField.getPassword());
        String names = txtName.getText();
        ArrayList<String> uNC= new ArrayList<String>();
        for(UserAccount u:ep.getUserAccountDirectory().getUserAccountList())
        {
            uNC.add(u.getUsername());
           
        }
        if(uNC.contains(user))
        {
            JOptionPane.showMessageDialog(null, "Above Name Already exists please enter a new name");
            return;
        }
        
        Employee emp = ep.getEmployeeDirectory().createEmployee(names);
        
        UserAccount account = ep.getUserAccountDirectory().createUserAccount(user, passcode, emp, new AdminRole());
        tblPopulate();
         txtUserName.setText("");
         passwordJPasswordField.setText("");
         txtName.setText("");
         
         
         
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        workArea.remove(this);
         Component[] cA = workArea.getComponents();
        Component comp = cA[cA.length - 1];
        AdminSystemWorkAreaJPanel sysAdminwjp = (AdminSystemWorkAreaJPanel) comp;
        sysAdminwjp.tblPopulateData();
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox enterpriseComboBox;
    private javax.swing.JTable enterprisesJTab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterPriseAdmin;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNetwork;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JComboBox networkComboBox;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
