package userinterface.DrugCompoundSupplierWorkArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Business.BioChemicalCompound.BioChemicalCompound;
import Business.DrugRegulator.DrugRegulator;
import Business.DrugRegulator.DrugRegulatorList;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.DrugCompounds.DrugCompounds;
import Business.Network.Network;
import Business.Organization.DrugOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanatpopli
 */
public class ChemicalCompoundsWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChemicalCompoundsWorkAreaJPanel
     */
    private DrugRegulator drugReg;
    private DrugRegulatorList drugRegList;
     private JPanel userProcessContainer;
    private EcoSystem es;
    private UserAccount userAccount;
    private DrugOrganization drugOrg ;
    private Enterprise erp;
    private Object obj;
    
    private Network network;
    public ChemicalCompoundsWorkAreaJPanel(JPanel userProcessContainer,EcoSystem es,UserAccount userAccount,DrugOrganization drugOrg,Enterprise erp,Network network,DrugRegulator drugReg) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.es = es;
        this.erp = erp;
        this.network = network;
        this.drugReg = drugReg;
        this.drugOrg = (DrugOrganization)drugOrg;
        tblPopulateData();
    }
    
    public void tblPopulateData(){
         DefaultTableModel dtm = (DefaultTableModel)tblChemicalDrug.getModel();
        
        dtm.setRowCount(0);
        Object[] row = new Object[2];
        int i = 0;
            for(BioChemicalCompound c : drugReg.getBioChemList().getBioChemicalCompoundList()){
                 
                 row[0] = c.getBioChemicalCompound();
                 
                    
                    DrugCompounds g=  drugReg.getDrugCompoundList().getDrugCompoundHistory().get(i);
                      
                      row[1] = g.getDrugCompound();
                      dtm.addRow(row);
                     i++;
                 }
                 
            
         
        
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblChemicalDrug = new javax.swing.JTable();
        txtChemicalCompound = new javax.swing.JTextField();
        txtDrugCompound = new javax.swing.JTextField();
        lblChemicalCompound = new javax.swing.JLabel();
        lblDrugCompound = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblChemicalDrug.setBackground(new java.awt.Color(255, 255, 153));
        tblChemicalDrug.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 20)); // NOI18N
        tblChemicalDrug.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chemical Compund", "Drug Compound"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChemicalDrug.setRowHeight(30);
        tblChemicalDrug.getTableHeader().setResizingAllowed(false);
        tblChemicalDrug.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblChemicalDrug);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 139, 630, 150));

        txtChemicalCompound.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 20)); // NOI18N
        txtChemicalCompound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChemicalCompoundActionPerformed(evt);
            }
        });
        add(txtChemicalCompound, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 200, -1));

        txtDrugCompound.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 20)); // NOI18N
        add(txtDrugCompound, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 423, 200, -1));

        lblChemicalCompound.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblChemicalCompound.setText("Chemical Compound");
        add(lblChemicalCompound, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

        lblDrugCompound.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblDrugCompound.setText("Drug Compound");
        add(lblDrugCompound, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 210, -1));

        btnAdd.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 24)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, 110, -1));

        btnBack.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 24)); // NOI18N
        btnBack.setText(" Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, -1, -1));

        lblTitle.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        lblTitle.setText("Drug and Chemical Compounds");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 400, 53));
    }// </editor-fold>//GEN-END:initComponents

    private void txtChemicalCompoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChemicalCompoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChemicalCompoundActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
         String chemicalName = txtChemicalCompound.getText().trim();
         String drugName = txtDrugCompound.getText().trim();
         if(chemicalName.isEmpty())
         {
             JOptionPane.showMessageDialog(null,"Please enter the chemical name");
             return;
         }
         if(drugName.isEmpty())
         {
             JOptionPane.showMessageDialog(null, "please enter the drug name ");
             return;
         }
         ArrayList<String> chemicalCheck = new ArrayList<>();
         for(BioChemicalCompound c : drugReg.getBioChemList().getBioChemicalCompoundList())
         {
             chemicalCheck.add(c.getBioChemicalCompound().toLowerCase());
             
         }
         ArrayList<String>drugcheck= new ArrayList<>();
         for(DrugCompounds g:drugReg.getDrugCompoundList().getDrugCompoundHistory())
         {
             drugcheck.add(g.getDrugCompound().toLowerCase());
         }
         if(chemicalCheck.contains(chemicalName.toLowerCase()))
         {
             JOptionPane.showMessageDialog(null,"Chemical already exists in the drug ");
             return;
             
         }
         if(drugcheck.contains(drugName.toLowerCase()))
         {
          JOptionPane.showMessageDialog(null,"Drug Compound already exists in the drug ");
             return;   
         }
        drugReg.getBioChemList().addChemicalList().setBioChemicalCompound(chemicalName);
        drugReg.getDrugCompoundList().addDrugCompoundList().setDrugCompound(drugName);
       
        tblPopulateData();
        txtChemicalCompound.setText("");
        txtDrugCompound.setText("");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component comp = componentArray[componentArray.length - 1];
        DrugCompoundWorkAreaJPanel dcjp = (DrugCompoundWorkAreaJPanel) comp;
        dcjp.tblPopulateData();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChemicalCompound;
    private javax.swing.JLabel lblDrugCompound;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblChemicalDrug;
    private javax.swing.JTextField txtChemicalCompound;
    private javax.swing.JTextField txtDrugCompound;
    // End of variables declaration//GEN-END:variables
}
