package userinterface.DrugCompoundSupplierWorkArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Business.BioChemicalCompoundInventory.BioChemicalCompoundInventory;
import Business.Enterprise.Enterprise;
import Business.MedicalInventory.MedicalInventory;
import Business.MedicalInventory.MedicalInventoryList;
import Business.Organization.DrugOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author nisha
 * 
 */
public class DisplayChemicalCompoundsDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayChemicalCompoundsDetailsJPanel
     */
    JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise erp;
    private MedicalInventoryList mil;
    private DrugOrganization drugOrg;
    private BioChemicalCompoundInventory ci;
    private static final String CLASS_NAME = DisplayChemicalCompoundsDetailsJPanel.class.getName();
    public DisplayChemicalCompoundsDetailsJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise erp,BioChemicalCompoundInventory ci) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.erp=erp;
        this.drugOrg= drugOrg;
        this.ci=ci;
       
            
        txtSerialNumber.setText(String.valueOf(ci.getSerialNumber()));
        txtAvailability.setText(String.valueOf(ci.getTotalAvailableQuantity()));
        txtChemicalCompoundName.setText(ci.getBioChemCompound());
        btnSave.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSerialNumber = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();
        lblChemicalCompoundName = new javax.swing.JLabel();
        txtChemicalCompoundName = new javax.swing.JTextField();
        lblAvailability = new javax.swing.JLabel();
        txtAvailability = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblTittle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSerialNumber.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblSerialNumber.setText("Serial Number:");
        add(lblSerialNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, 30));

        txtSerialNumber.setEditable(false);
        txtSerialNumber.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        txtSerialNumber.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(txtSerialNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 207, -1));

        lblChemicalCompoundName.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblChemicalCompoundName.setText("Chemical Compound Name:");
        add(lblChemicalCompoundName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, 30));

        txtChemicalCompoundName.setEditable(false);
        txtChemicalCompoundName.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        txtChemicalCompoundName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(txtChemicalCompoundName, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 210, -1));

        lblAvailability.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblAvailability.setText("Availability:");
        add(lblAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, 30));

        txtAvailability.setEditable(false);
        txtAvailability.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        txtAvailability.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvailabilityActionPerformed(evt);
            }
        });
        add(txtAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 210, -1));

        btnBack.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnBack.setText(" BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 190, -1));

        btnSave.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 136, -1));

        btnUpdate.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 136, -1));

        lblTittle.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        lblTittle.setText("Chemical Compound Details");
        add(lblTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 360, 53));
    }// </editor-fold>//GEN-END:initComponents

    private void txtAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvailabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvailabilityActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component comp = componentArray[componentArray.length - 1];
        DisplayChemicalCompoundRequestWorkAreaJPanel dccrjp = (DisplayChemicalCompoundRequestWorkAreaJPanel) comp;
        dccrjp.tblReorder();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(txtChemicalCompoundName.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "chemical name is empty");
            return;
        }
        ci.setBioChemCompound(txtChemicalCompoundName.getText());
        
        try{
        int availableQuantity= Integer.parseInt(txtAvailability.getText());
        ci.setTotalAvailableQuantity(availableQuantity);
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Available quantity must be integer");
            return;
        }
        try{
        int serialNumber= Integer.parseInt(txtSerialNumber.getText());
        ci.setSerialNumber(serialNumber);
        }
         catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Serial number must be integer");
            return;
        }
        
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
         txtChemicalCompoundName.setEditable(false);
        txtSerialNumber.setEditable(false);
        txtAvailability.setEditable(false);

        JOptionPane.showMessageDialog(null, "Medicine updated Successfully", "Warning", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        txtChemicalCompoundName.setEditable(true);
        txtSerialNumber.setEditable(true);
        txtAvailability.setEditable(true);
        btnUpdate.setEnabled(false);
        btnSave.setEnabled(true);
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblChemicalCompoundName;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JTextField txtAvailability;
    private javax.swing.JTextField txtChemicalCompoundName;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
