package userinterface.DrugCompoundSupplierWorkArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Business.Enterprise.Enterprise;
import Business.Organization.DrugOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ChemicalWorkRequest;
import Business.WorkQueue.DrugWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nisha
 */
public class DisplayRequestsWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayRequestsWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise erp;
    private DrugOrganization drugOrg;
    private static final String CLASS_NAME = DisplayRequestsWorkAreaJPanel.class.getName();
    public DisplayRequestsWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise erp, DrugOrganization drugOrg) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.erp = erp;
        this.drugOrg = drugOrg;
        tblPopulateData();
    }
    
    public void tblPopulateData(){
        DefaultTableModel dtm = (DefaultTableModel)drugRequestsTable.getModel();
        
        dtm.setRowCount(0);
        
        
      // for(WorkRequest req : opOrganization.getWorkQueue().getWorkRequestList())
      
        
        dtm.setRowCount(0);
        for (WorkRequest req : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[5];
            row[0] = ((ChemicalWorkRequest) req);
            row[1] = ((ChemicalWorkRequest) req).getQuantity();
            row[2] = req.getReceiver();
            String result = ((ChemicalWorkRequest) req).getStatus();
            row[3] = result == null ? "Waiting" : result;
            if(((ChemicalWorkRequest) req).getDeliveryTime()==null){
                row[4]="Details yet to be updated by supplier";
            }
            else{
            row[4]  = "Expected delivery time " +((ChemicalWorkRequest) req).getDeliveryTime();
                    }
            
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        drugRequestsTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        drugRequestsTable.setBackground(new java.awt.Color(255, 255, 153));
        drugRequestsTable.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        drugRequestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CHEMICAL COMPOUND NAME", "REQUIRED QUANTITY", "RECIEVER", "STATUS", "DELIVERY DATE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        drugRequestsTable.setRowHeight(30);
        jScrollPane.setViewportView(drugRequestsTable);

        add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 158, 1045, 277));

        btnBack.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 136, -1));

        lblTitle.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        lblTitle.setText("View Requests");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 190, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component comp = componentArray[componentArray.length - 1];
        DisplayChemicalCompoundRequestWorkAreaJPanel dccrjp = (DisplayChemicalCompoundRequestWorkAreaJPanel) comp;
        dccrjp.tblReorder();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JTable drugRequestsTable;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
