package userinterface.DrugCompoundSupplierWorkArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Business.BioChemicalCompound.BioChemicalCompound;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DrugOrganization;
import static Business.Organization.Organization.Type.Drug;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import Business.DrugRegulator.DrugRegulator;
import Business.DrugCompounds.DrugCompounds;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bhagyatrivedi
 */
public class DrugReportsHistoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrugReportsHistoryJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem es;
    private UserAccount userAccount;
    private DrugOrganization drugOrg ;
    private Enterprise erp;
    private Network network;
    private DrugRegulator drugReg;
    public DrugReportsHistoryJPanel(JPanel userProcessContainer,UserAccount userAccount,Enterprise erp, DrugOrganization drugOrg,Network network,DrugRegulator drugReg) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.drugOrg = drugOrg;
        this.erp = erp;
        this.network = network;
        this.drugReg=drugReg;
        tblPopulateData();
        txtDrugName.setText(drugReg.getDrug());
        
    }
    
    public void tblPopulateData(){
         DefaultTableModel dtm = (DefaultTableModel)tblChemicalDrug.getModel();
        
        dtm.setRowCount(0);
        Object[] row = new Object[2];
        int i = 0;
            for(BioChemicalCompound ci : drugReg.getBioChemList().getBioChemicalCompoundList()){
                 
                 row[0] = ci.getBioChemicalCompound();
                 
                    
                    DrugCompounds dc=  drugReg.getDrugCompoundList().getDrugCompoundHistory().get(i);
                      
                      row[1] = dc.getDrugCompound();
                      dtm.addRow(row);
                     i++;
                 }
                 
            
         
        
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblChemicalDrug = new javax.swing.JTable();
        txtDrugName = new javax.swing.JTextField();
        lblDrugName = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setForeground(new java.awt.Color(0, 0, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblChemicalDrug.setBackground(new java.awt.Color(255, 255, 153));
        tblChemicalDrug.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 20)); // NOI18N
        tblChemicalDrug.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chemical Compound Name", "Drug Compound Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChemicalDrug.setRowHeight(30);
        tblChemicalDrug.getTableHeader().setResizingAllowed(false);
        tblChemicalDrug.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblChemicalDrug);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 249, 630, 150));

        txtDrugName.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        txtDrugName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrugNameActionPerformed(evt);
            }
        });
        add(txtDrugName, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 290, -1));

        lblDrugName.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblDrugName.setText("Drug Name");
        add(lblDrugName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 169, -1));

        btnBack.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, -1, 33));

        lblTitle.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        lblTitle.setText("Existing Drug");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 190, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void txtDrugNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrugNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrugNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component comp = componentArray[componentArray.length - 1];
        LabReportsWorkAreaJPanel lrwjp = (LabReportsWorkAreaJPanel) comp;
        lrwjp.tblPopulateData();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDrugName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblChemicalDrug;
    private javax.swing.JTextField txtDrugName;
    // End of variables declaration//GEN-END:variables
}
