package userinterface.DrugCompoundSupplierWorkArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Business.DrugRegulator.DrugRegulator;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DrugOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author bhagyatrivedi
 */
public class DrugCompoundJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrugCompoundJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem es;
    private UserAccount userAccount;
    private DrugOrganization drugOrg ;
    private Enterprise erp;
    private Network network;
    public DrugCompoundJPanel(JPanel userProcessContainer,UserAccount userAccount,Enterprise erp, DrugOrganization drugOrg,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.drugOrg = drugOrg;
        this.erp = erp;
        this.network = network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNewDrugIdentify = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNewDrugIdentify.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblNewDrugIdentify.setText("New Drug Compound has been Identified ");
        add(lblNewDrugIdentify, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 530, 132));

        btnBack.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, 33));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component comp = componentArray[componentArray.length - 1];
        LabReportsWorkAreaJPanel lrwjp = (LabReportsWorkAreaJPanel) comp;
        lrwjp.tblPopulateData();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblNewDrugIdentify;
    // End of variables declaration//GEN-END:variables
}
