package userinterface.DrugCompoundSupplierWorkArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Business.DrugRegulator.DrugRegulatorList;
import Business.DrugRegulator.DrugRegulator;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DrugOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bhagyatrivedi
 */
public class DrugCompoundWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrugCompoundWorkAreaJPanel
     */
    private DrugRegulatorList drugRegList;
    private JPanel userProcessContainer;
    private EcoSystem es;
    private UserAccount userAccount;
    private DrugOrganization drugOrg;
    private Enterprise erp;
    private Network network;
    private static final String CLASS_NAME = DrugCompoundWorkAreaJPanel.class.getName();

    public DrugCompoundWorkAreaJPanel(JPanel userProcessContainer, EcoSystem es, UserAccount userAccount, DrugOrganization drugOrg, Enterprise erp, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.es = es;
        this.erp = erp;
        this.network = network;
        this.drugOrg = drugOrg;
        tblPopulateData();

    }

    public void tblPopulateData() {
        DefaultTableModel dtm = (DefaultTableModel) tblDrug.getModel();

        dtm.setRowCount(0);

        for (DrugRegulator dr : es.getDrugList().getDrugList()) {

            Object[] row = new Object[2];
            row[0] = dr.getDrugId();
            row[1] = dr;
            dtm.addRow(row);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrug = new javax.swing.JTable();
        txtDrug = new javax.swing.JTextField();
        btnAddDrug = new javax.swing.JButton();
        lblDrug = new javax.swing.JLabel();
        btnAddChemicalCompound = new javax.swing.JButton();
        btnButton = new javax.swing.JButton();
        processlbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDrug.setBackground(new java.awt.Color(255, 255, 153));
        tblDrug.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 20)); // NOI18N
        tblDrug.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DrugName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDrug.setRowHeight(30);
        jScrollPane1.setViewportView(tblDrug);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 141, 720, 270));

        txtDrug.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 20)); // NOI18N
        txtDrug.setForeground(new java.awt.Color(0, 0, 102));
        txtDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrugActionPerformed(evt);
            }
        });
        add(txtDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 230, 40));

        btnAddDrug.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnAddDrug.setText("ADD Drug");
        btnAddDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDrugActionPerformed(evt);
            }
        });
        add(btnAddDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 431, 180, -1));

        lblDrug.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblDrug.setText("Drug");
        add(lblDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 431, 80, 40));

        btnAddChemicalCompound.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnAddChemicalCompound.setText("Add Chemical Compound");
        btnAddChemicalCompound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddChemicalCompoundActionPerformed(evt);
            }
        });
        add(btnAddChemicalCompound, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, -1, -1));

        btnButton.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnButton.setText(" Back");
        btnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnButtonActionPerformed(evt);
            }
        });
        add(btnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 90, 40));

        processlbl.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        processlbl.setText("Drug Panel");
        add(processlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 170, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void txtDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrugActionPerformed

    private void btnAddDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDrugActionPerformed
        // TODO add your handling code here:

        String drugName = txtDrug.getText().trim();
        if(drugName.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Drug name cannot be empty");
            return;
        }
        ArrayList<String> drugcheck= new ArrayList<>();
        for(DrugRegulator dreg:es.getDrugList().getDrugList())
        {
            drugcheck.add(dreg.getDrug().toLowerCase());
        }
        if(drugcheck.contains(drugName.toLowerCase()))
        {
            JOptionPane.showMessageDialog(null,"Drug name already exists");
            return;
        }

        es.getDrugList().addDrugList().setDrug(drugName);
        
        tblPopulateData();
        txtDrug.setText("");

    }//GEN-LAST:event_btnAddDrugActionPerformed

    private void btnAddChemicalCompoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddChemicalCompoundActionPerformed
        // TODO add your handling code here:
        int index = tblDrug.getSelectedRow();
        if(index<0)
        {
            JOptionPane.showMessageDialog(null, "please select a row ");
            return;
        }
        DrugRegulator dr = (DrugRegulator) tblDrug.getValueAt(index, 1);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("AddChemicalsJPanel", new ChemicalCompoundsWorkAreaJPanel(userProcessContainer, es, userAccount, drugOrg, erp, network, dr));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddChemicalCompoundActionPerformed

    private void btnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddChemicalCompound;
    private javax.swing.JButton btnAddDrug;
    private javax.swing.JButton btnButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDrug;
    private javax.swing.JLabel processlbl;
    private javax.swing.JTable tblDrug;
    private javax.swing.JTextField txtDrug;
    // End of variables declaration//GEN-END:variables
}
