/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PharmaWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DrugWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanatpopli
 */
public class DisplayRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayRequestsJPanel
     */
    
     private JPanel workArea;
    private EcoSystem business;
    private UserAccount uA;
    private Organization org;
    private Enterprise ep;
    private static final String CLASS_NAME = DisplayRequestsJPanel.class.getName();
    public DisplayRequestsJPanel(JPanel workArea,UserAccount uA,Enterprise ep,Organization org) {
        initComponents();
        this.workArea=workArea;
        this.uA=uA;
        this.ep=ep;
        this.org= org;
        tblPopulate();
    }
    
    public void tblPopulate(){
        DefaultTableModel mod = (DefaultTableModel)tblRequest.getModel();
        
        mod.setRowCount(0);
        
        
      // for(WorkRequest req : opOrganization.getWorkQueue().getWorkRequestList())
      
        
        mod.setRowCount(0);
        for (WorkRequest req : uA.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[5];
            row[0] = ((DrugWorkRequest) req).getDrugName();
            row[1] = ((DrugWorkRequest) req).getQuantity();
            row[2] = req.getReceiver();
            String result = ((DrugWorkRequest) req).getStatus();
            row[3] = result == null ? "Waiting" : result;
            if(((DrugWorkRequest) req).getDeliveryTime()==null){
                row[4]="Details yet to be updated by supplier";
            }
            else{
            row[4]  = "delivery time " +((DrugWorkRequest) req).getDeliveryTime();
                    }
            
            mod.addRow(row);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        tblRequest = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        lblReqmedicine = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRequest.setBackground(new java.awt.Color(255, 255, 153));
        tblRequest.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 20)); // NOI18N
        tblRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MEDICINE NAME", "REQUIRED QUANTITY", "RECIEVER", "STATUS", "DELIVERY DATE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRequest.setRowHeight(25);
        jScrollPane.setViewportView(tblRequest);

        add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 208, 1140, 277));

        backBtn.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        backBtn.setText(" BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 590, 136, -1));

        btnRefresh.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 590, 160, -1));

        lblReqmedicine.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lblReqmedicine.setText("Requested Medicine Info");
        add(lblReqmedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
       workArea.remove(this);
        Component[] componentArray = workArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PharmaWorkAreaJPanel dw = (PharmaWorkAreaJPanel) component;
        dw.tblReorder();
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_backBtnActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblReqmedicine;
    private javax.swing.JTable tblRequest;
    // End of variables declaration//GEN-END:variables
}
