/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LabWorkArea;

import Business.Doctor.Patient;
import Business.Enterprise.Enterprise;
import Business.DrugCompounds.DrugCompounds;
import Business.Network.Network;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DrugWorkRequest;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.DoctorWorkArea.DoctorPrescWorkAreaJPanel;

/**
 *
 * @author sanatpopli
 *
 */
public class LabRequestWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel workArea;
    private LabTestWorkRequest req;
    private LabOrganization lOrg;
    private UserAccount uA;
    private Network nW;
    String filePath = "./drug data.txt";

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public LabRequestWorkAreaJPanel(JPanel workArea, LabTestWorkRequest req, Organization org, UserAccount uA, Network nW) {
        initComponents();
        this.workArea = workArea;
        this.req = req;
        this.uA = uA;
        this.nW = nW;
        this.lOrg = (LabOrganization) org;
        txtPatientName.setText(req.getPatientName());

        tblPopulate();
        System.out.println(req.getStatus());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmit = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        tblGene = new javax.swing.JTable();
        lblPatientName = new javax.swing.JLabel();
        btnCreateDrug = new javax.swing.JButton();
        lblDrugCompound = new javax.swing.JLabel();
        txtDrugC = new javax.swing.JTextField();
        lblImg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubmit.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btnSubmit.setText("Submit Result");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 570, -1, -1));

        lblResult.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lblResult.setText("Lab Request Work Area ");
        add(lblResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        txtPatientName.setEditable(false);
        txtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientNameActionPerformed(evt);
            }
        });
        add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 240, 30));

        btnBack.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 140, -1));

        tblGene.setBackground(new java.awt.Color(255, 255, 153));
        tblGene.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        tblGene.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug ID", "Drug Compound"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGene.setRowHeight(30);
        jScrollPane.setViewportView(tblGene);
        if (tblGene.getColumnModel().getColumnCount() > 0) {
            tblGene.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 560, 280));

        lblPatientName.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblPatientName.setText("Patient Name :");
        add(lblPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 180, 30));

        btnCreateDrug.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btnCreateDrug.setText("Create Drug");
        btnCreateDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDrugActionPerformed(evt);
            }
        });
        add(btnCreateDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 480, 160, -1));

        lblDrugCompound.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblDrugCompound.setText("Drug Compound");
        add(lblDrugCompound, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 190, 40));

        txtDrugC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrugCActionPerformed(evt);
            }
        });
        add(txtDrugC, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, 180, 40));

        lblImg.setBackground(new java.awt.Color(153, 204, 255));
        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sayNoToDrugs.png"))); // NOI18N
        add(lblImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 530, 280));
    }// </editor-fold>//GEN-END:initComponents

    public void tblPopulate() {
        DefaultTableModel mod = (DefaultTableModel) tblGene.getModel();

        mod.setRowCount(0);
        System.out.println(((LabTestWorkRequest) req).getPatient().getDrugHistory().getDrugCompoundHistory());
        System.out.println(((LabTestWorkRequest) req).getPatient().getDrugHistory().getDrugCompoundHistory().size());
        
        Patient pat = ((LabTestWorkRequest)req).getPatient();
        ArrayList<DrugCompounds> dCH = pat.getDrugHistory().getDrugCompoundHistory();
        for (DrugCompounds g : dCH) {
            
            String drugCompound = g.getDrugCompound();
            int idl = g.getId();
            
            Object[] row = new Object[2];
            row[0] = idl;
            row[1] = drugCompound;
            System.out.println(((LabTestWorkRequest) req).getPatient());

            mod.addRow(row);
        }

    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        workArea.remove(this);
        Component[] cA = workArea.getComponents();
        Component component = cA[cA.length - 1];
        LabWorkAreaJPanel panel = (LabWorkAreaJPanel) component;
        panel.populateTable();
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        btnSubmit.setEnabled(true);
        ArrayList<String> drugAvail = new ArrayList<>();
        Patient p = ((LabTestWorkRequest)req).getPatient();
        ArrayList<DrugCompounds> drugCompoundHistory = p.getDrugHistory().getDrugCompoundHistory();
        for (DrugCompounds g : drugCompoundHistory) {
            drugAvail.add(g.getDrugCompound());

        }
        if (drugAvail.size() <= 0) {
            JOptionPane.showMessageDialog(null, "No drugs is available!");
            return;
        }
        req.setStatus("Complete");
        DrugWorkRequest dWR = new DrugWorkRequest();
        Patient patient = ((LabTestWorkRequest) req).getPatient();
        dWR.setPatient(patient);

        dWR.setSender(uA);
        ArrayList<WorkRequest> workRequestList = uA.getWorkQueue().getWorkRequestList();
        workRequestList.add(dWR);
        ArrayList<Enterprise> enterpriseList = nW.getEnterpriseDirectory().getEnterpriseList();
        for (Enterprise ep : enterpriseList) {
            ArrayList<Organization> organizationList = ep.getOrganizationDirectory().getOrganizationList();
            for (Organization org : organizationList) {
                if (org.getName().equals("Drug Organization")) {
                    ArrayList<WorkRequest> workRequestList1 = org.getWorkQueue().getWorkRequestList();
                    workRequestList1.add(dWR);
                }
            }

        }
        JOptionPane.showMessageDialog(null, "Result has been succesfully submited");
        btnSubmit.setEnabled(false);


    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtDrugCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrugCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrugCActionPerformed

    private void btnCreateDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDrugActionPerformed
        // TODO add your handling code here:
        Patient patient = ((LabTestWorkRequest) req).getPatient();
        String drugName = txtDrugC.getText().trim();
        if (drugName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please add the Drug!");
            return;
        }

        ArrayList<String> drugAvail = new ArrayList<>();
        ArrayList<DrugCompounds> drugCompoundHistory = patient.getDrugHistory().getDrugCompoundHistory();
        for (DrugCompounds g1 : drugCompoundHistory) {
            drugAvail.add(g1.getDrugCompound().toLowerCase());
        }
        if (drugAvail.contains(drugName.toLowerCase())) {
            JOptionPane.showMessageDialog(null, "Drug is already in the cart!");
            return;
        }
        DrugCompounds dc = patient.getDrugHistory().addDrugCompoundList();
        dc.setDrugCompound(drugName);
        req.setPatient(patient);
        tblPopulate();
        saveRecord(dc.getDrugCompound());
        txtDrugC.setText("");

    }//GEN-LAST:event_btnCreateDrugActionPerformed

    private void txtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNameActionPerformed

    public void saveRecord(String drug) {
        try {
            FileWriter files = new FileWriter(filePath, true);
            BufferedWriter buffer = new BufferedWriter(files);
            PrintWriter printer = new PrintWriter(buffer);
            printer.println(drug);
            printer.flush();
            printer.close();
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(DoctorPrescWorkAreaJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateDrug;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lblDrugCompound;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblResult;
    private javax.swing.JTable tblGene;
    private javax.swing.JTextField txtDrugC;
    private javax.swing.JTextField txtPatientName;
    // End of variables declaration//GEN-END:variables

}
