/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdminWorkArea;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author bhagyatrivedi
 */
public class AdministrativeWorkAreaJPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form AdministrativeWorkAreaJPanel
     */
    JPanel workArea;
    Enterprise ep;
    public AdministrativeWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
         this.ep = enterprise;
          this.workArea = userProcessContainer;
          lblval.setText(enterprise.getName());
       
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdminWorkArea = new javax.swing.JLabel();
        lblval = new javax.swing.JLabel();
        manageEmployeebtn = new javax.swing.JButton();
        lblEnterprise = new javax.swing.JLabel();
        userbtn = new javax.swing.JButton();
        btnOrgManagement = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdminWorkArea.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblAdminWorkArea.setText("Admin Work Area");
        add(lblAdminWorkArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        lblval.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblval.setText("<value>");
        add(lblval, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 130, 30));

        manageEmployeebtn.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        manageEmployeebtn.setText("Employee Management");
        manageEmployeebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeebtnActionPerformed(evt);
            }
        });
        add(manageEmployeebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 330, 70));

        lblEnterprise.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblEnterprise.setText("Enterprise :");
        add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 150, 30));

        userbtn.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        userbtn.setText("User Management");
        userbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userbtnActionPerformed(evt);
            }
        });
        add(userbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 610, 330, 70));

        btnOrgManagement.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnOrgManagement.setText("Organization Management");
        btnOrgManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrgManagementActionPerformed(evt);
            }
        });
        add(btnOrgManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 340, 70));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, -30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrgManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrgManagementActionPerformed
        // TODO add your handling code here:
        OrgManagementWorkAreaJPanel panel = new OrgManagementWorkAreaJPanel(workArea, ep.getOrganizationDirectory(),ep);
        workArea.add("OrgManagementWorkAreaJPanel", panel);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnOrgManagementActionPerformed

    private void manageEmployeebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeebtnActionPerformed
        // TODO add your handling code here:
        int orgCount=0;
        for(Organization o: ep.getOrganizationDirectory().getOrganizationList())
        {
            orgCount++;
            
        }
        if(orgCount<=0)
        {
            JOptionPane.showMessageDialog(null, "Unable to create employee!");
            return;
        }
        
        EmpManagementWorkAreaJPanel panel = new EmpManagementWorkAreaJPanel(workArea, ep.getOrganizationDirectory());
        workArea.add("EmpManagementWorkAreaJPanel", panel);

        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_manageEmployeebtnActionPerformed

    private void userbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userbtnActionPerformed
        // TODO add your handling code here:
        int empCount=0;
        for(Organization o: ep.getOrganizationDirectory().getOrganizationList())
        {
            for(Employee e :o.getEmployeeDirectory().getEmployeeList())
            empCount++;
            
        }
        if(empCount<=0)
        {
             JOptionPane.showMessageDialog(null, "No emp to create user!");
            return;
        }
        UsrManagementWorkAreaJPanel panel = new UsrManagementWorkAreaJPanel(workArea, ep);
        workArea.add("UsrManagementWorkAreaJPanel", panel);

        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_userbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrgManagement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAdminWorkArea;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblval;
    private javax.swing.JButton manageEmployeebtn;
    private javax.swing.JButton userbtn;
    // End of variables declaration//GEN-END:variables
}
