/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdminWorkArea;

import Business.Employee.Employee;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bhagyatrivedi
 */
public class EmpManagementWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmpManagementWorkAreaJPanel
     */
    private OrganizationDirectory orgDirectory;
    private JPanel workArea;
        public EmpManagementWorkAreaJPanel(JPanel workArea, OrganizationDirectory orgDirectory) {
        initComponents();
        this.workArea = workArea;
        this.orgDirectory = orgDirectory;               
        empOrgCBPopulate();
        orgCBPopulate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblOrganization = new javax.swing.JLabel();
        comboBoxOrg = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrg = new javax.swing.JTable();
        lblOrg = new javax.swing.JLabel();
        comboBoxEmpOrg = new javax.swing.JComboBox();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        addJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblTitle.setText("Manage Employee");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 40, 470, -1));

        lblOrganization.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblOrganization.setText("Organization:");
        add(lblOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 133, -1, -1));

        comboBoxOrg.setBackground(new java.awt.Color(255, 255, 153));
        comboBoxOrg.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        comboBoxOrg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxOrgActionPerformed(evt);
            }
        });
        add(comboBoxOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 137, 270, 32));

        tblOrg.setBackground(new java.awt.Color(255, 255, 153));
        tblOrg.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        tblOrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrg.setRowHeight(25);
        tblOrg.getTableHeader().setResizingAllowed(false);
        tblOrg.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblOrg);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 242, 547, 165));

        lblOrg.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblOrg.setText("Organization:");
        add(lblOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 490, -1, -1));

        comboBoxEmpOrg.setBackground(new java.awt.Color(255, 255, 153));
        comboBoxEmpOrg.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 20)); // NOI18N
        comboBoxEmpOrg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxEmpOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEmpOrgActionPerformed(evt);
            }
        });
        add(comboBoxEmpOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 494, 300, 32));

        txtName.setBackground(new java.awt.Color(255, 255, 153));
        txtName.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 20)); // NOI18N
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 556, 300, 40));

        lblName.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblName.setText("Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 552, -1, -1));

        backJButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 690, -1, -1));

        addJButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        addJButton.setText("Create Employee");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 690, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
         workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        // TODO add your handling code here:
        Organization org = (Organization) comboBoxEmpOrg.getSelectedItem();
        String name = txtName.getText().trim();
        if(name.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please enter name!");
            return;
        }
        ArrayList<String> isNameAvailList = new ArrayList<>();
        for(Employee o:org.getEmployeeDirectory().getEmployeeList())
        {
            isNameAvailList.add(o.getName().toLowerCase());
            
        }
        if(isNameAvailList.contains(name.toLowerCase()))
        {
            JOptionPane.showMessageDialog(null,"Employee is already registered!");
            return;
        }
        org.getEmployeeDirectory().createEmployee(name);
        populateEmployeeTbl(org);
        txtName.setText("");
    }//GEN-LAST:event_addJButtonActionPerformed

    private void comboBoxOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxOrgActionPerformed
        // TODO add your handling code here:
         Organization org = (Organization) comboBoxOrg.getSelectedItem();
        if (org != null){
            populateEmployeeTbl(org);
        }
    }//GEN-LAST:event_comboBoxOrgActionPerformed

    private void comboBoxEmpOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEmpOrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxEmpOrgActionPerformed
 public void orgCBPopulate(){
        comboBoxOrg.removeAllItems();
        
        for (Organization org : orgDirectory.getOrganizationList()){
            comboBoxOrg.addItem(org);
        }
    }
 public void empOrgCBPopulate(){
        comboBoxEmpOrg.removeAllItems();
        
        for (Organization org : orgDirectory.getOrganizationList()){
            comboBoxEmpOrg.addItem(org);
        }
    }
 private void populateEmployeeTbl(Organization organization){
        DefaultTableModel dtm = (DefaultTableModel) tblOrg.getModel();
        
        dtm.setRowCount(0);
        
        for (Employee e : organization.getEmployeeDirectory().getEmployeeList()){
            Object[] row = new Object[2];
            row[0] = e.getId();
            row[1] = e.getName();
            dtm.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox comboBoxEmpOrg;
    private javax.swing.JComboBox comboBoxOrg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrg;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblOrg;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
