/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdminWorkArea;

import Business.Employee.EmployeeDirectory;
import Business.Enterprise.ChemicalEnterprise;
import Business.Enterprise.DrugEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bhagyatrivedi
 */
public class OrgManagementWorkAreaJPanel extends javax.swing.JPanel {

      private OrganizationDirectory orgDirectory;
      private JPanel workArea;
      private Enterprise ep;
    /**
     * Creates new form ManageOrganizationJpanel
     */
    public OrgManagementWorkAreaJPanel(JPanel workArea,OrganizationDirectory orgDirectory,Enterprise ep) {
        initComponents();
        this.orgDirectory = orgDirectory;
        this.workArea = workArea;
        this.ep=ep;
        populateTable();
        populateComboBox();
        
    }
    private void populateComboBox(){
        comboBoxOrg.removeAllItems();
        for (Organization.Type orgType : Organization.Type.values()){
            
            if (!orgType.getValue().equals(Organization.Type.Admin.getValue()))
            {
                EmployeeDirectory employeeDirectory = ep.getEmployeeDirectory();
                Enterprise.EnterpriseType enterpriseType = ep.getEnterpriseType();
                OrganizationDirectory organizationDirectory = ep.getOrganizationDirectory();
                
                if(ep instanceof HospitalEnterprise){
                    
                     comboBoxOrg.addItem(Organization.Type.Doctor);
                     comboBoxOrg.addItem(Organization.Type.Lab);
                     break;
                }else if(ep instanceof PharmacyEnterprise){
                    
                     comboBoxOrg.addItem(Organization.Type.Pharmacy);
                     break;
                    
                }
                else if(ep instanceof DrugEnterprise)
                {
                     comboBoxOrg.addItem(Organization.Type.Drug);
                     break;
                }
                else if(ep instanceof ChemicalEnterprise)
                {
                  comboBoxOrg.addItem(Organization.Type.Chemical);
                     break;  
                }
                 
                    
            }
        }
    }
     private void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblOrg.getModel();
        
        dtm.setRowCount(0);
        
        for (Organization org : orgDirectory.getOrganizationList()){
            Object[] row = new Object[2];
            row[0] = org.getOrganizationID();
            row[1] = org.getName();
            
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOrgManagement = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrg = new javax.swing.JTable();
        lblOrgType = new javax.swing.JLabel();
        comboBoxOrg = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();
        btnAddOrg = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOrgManagement.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 48)); // NOI18N
        lblOrgManagement.setText("Organization Management");
        add(lblOrgManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, -1));

        tblOrg.setBackground(new java.awt.Color(255, 255, 153));
        tblOrg.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        tblOrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Org ID", "Org Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrg.setRowHeight(22);
        tblOrg.getTableHeader().setResizingAllowed(false);
        tblOrg.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblOrg);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 198, 516, 177));

        lblOrgType.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblOrgType.setText("Organization Type: ");
        add(lblOrgType, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 444, -1, -1));

        comboBoxOrg.setBackground(new java.awt.Color(255, 255, 153));
        comboBoxOrg.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        comboBoxOrg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboBoxOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 450, 200, 32));

        btnBack.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnBack.setText(" Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, -1, -1));

        btnAddOrg.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnAddOrg.setText("Add Organization");
        btnAddOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrgActionPerformed(evt);
            }
        });
        add(btnAddOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1033, 538, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        workArea.remove(this);
        CardLayout cl = (CardLayout) workArea.getLayout();
        cl.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrgActionPerformed

        Type type = (Type) comboBoxOrg.getSelectedItem();
        orgDirectory.createOrganization(type);
        populateTable();
        
    }//GEN-LAST:event_btnAddOrgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrg;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox comboBoxOrg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOrgManagement;
    private javax.swing.JLabel lblOrgType;
    private javax.swing.JTable tblOrg;
    // End of variables declaration//GEN-END:variables
}
