/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkArea.Student;

import Business.Business;
import Business.Course.Course;
import Business.Profiles.StudentProfile;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Bhagya
 */
public class ViewSelectedAvailableCourseDetailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewSelectedAvailableCourseDetailJPanel
     */
    JPanel workArea;
    Business business;
    Course course;
    StudentProfile studentProfile;
    public ViewSelectedAvailableCourseDetailJPanel(JPanel workArea, Business business, Course course, StudentProfile studentProfile) {
        initComponents();
        this.workArea = workArea;
        this.business = business;
        this.course = course;
        this.studentProfile = studentProfile;
        populateValues();
    }
    
    public void populateValues(){
        txtCourseId.setText(course.getCourseId());
        ArrayList<String> courseAvailableforPrograms = course.getCourseAvailableforPrograms();
        String availProgs = "";
        for(String s : courseAvailableforPrograms){
            availProgs+=s;
            availProgs+=",";
        }
        txtAvailablePrograms.setText(availProgs);
        txtCourseName.setText(course.getCourseName());
        txtCredits.setText(course.getCredits());
        txtCrn.setText(course.getCrn());
        txtDayAndTime.setText(course.getClassDayAndTime());
        txtDegreesFor.setText(course.getOfferingDegree());
        txtProfId.setText(course.getProfId());
        txtProfName.setText(course.getProfName());
        txtProfRating.setText(course.getProfRating().toString());
        txtProgram.setText(course.getProgram());
        txtRoomBuilding.setText(course.getRoomAndBuildingLocation());
        txtTerm.setText(course.getOfferingTerm());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCrn = new javax.swing.JTextField();
        lblCourseId = new javax.swing.JLabel();
        lblCrn = new javax.swing.JLabel();
        txtTerm = new javax.swing.JTextField();
        lblRoomBuilding = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        txtRoomBuilding = new javax.swing.JTextField();
        lblProgram = new javax.swing.JLabel();
        lblCredits = new javax.swing.JLabel();
        txtProgram = new javax.swing.JTextField();
        lblDayAndTime = new javax.swing.JLabel();
        lblDegreesFor = new javax.swing.JLabel();
        lblProgramsFor = new javax.swing.JLabel();
        txtDegreesFor = new javax.swing.JTextField();
        txtCourseId = new javax.swing.JTextField();
        txtCredits = new javax.swing.JTextField();
        lblTerm = new javax.swing.JLabel();
        txtDayAndTime = new javax.swing.JTextField();
        txtCourseName = new javax.swing.JTextField();
        txtAvailablePrograms = new javax.swing.JTextField();
        txtProfName = new javax.swing.JTextField();
        lblProfName = new javax.swing.JLabel();
        txtProfId = new javax.swing.JTextField();
        lblProfId = new javax.swing.JLabel();
        lblProfRating = new javax.swing.JLabel();
        txtProfRating = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Selected Course Details");

        txtCrn.setMinimumSize(new java.awt.Dimension(250, 22));

        lblCourseId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCourseId.setText("Course Id:");

        lblCrn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCrn.setText("CRN:");

        txtTerm.setMinimumSize(new java.awt.Dimension(250, 22));

        lblRoomBuilding.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRoomBuilding.setText("Room and Building Location:");

        lblCourseName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCourseName.setText("Course Name : ");

        txtRoomBuilding.setMinimumSize(new java.awt.Dimension(250, 22));

        lblProgram.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProgram.setText("Program:");

        lblCredits.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCredits.setText("Credits: ");

        txtProgram.setMinimumSize(new java.awt.Dimension(250, 22));
        txtProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProgramActionPerformed(evt);
            }
        });

        lblDayAndTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDayAndTime.setText("Class Day and Time:");

        lblDegreesFor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDegreesFor.setText("Available for Degree:");

        lblProgramsFor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProgramsFor.setText("Available for Programs:");

        txtDegreesFor.setMinimumSize(new java.awt.Dimension(250, 22));
        txtDegreesFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDegreesForActionPerformed(evt);
            }
        });

        txtCourseId.setMinimumSize(new java.awt.Dimension(250, 22));

        txtCredits.setMinimumSize(new java.awt.Dimension(250, 22));

        lblTerm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTerm.setText("Term : ");

        txtDayAndTime.setMinimumSize(new java.awt.Dimension(250, 22));

        txtCourseName.setMinimumSize(new java.awt.Dimension(250, 22));

        txtAvailablePrograms.setMinimumSize(new java.awt.Dimension(250, 22));

        txtProfName.setMinimumSize(new java.awt.Dimension(250, 22));
        txtProfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfNameActionPerformed(evt);
            }
        });

        lblProfName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProfName.setText("Professor Name:");

        txtProfId.setMinimumSize(new java.awt.Dimension(250, 22));
        txtProfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfIdActionPerformed(evt);
            }
        });

        lblProfId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProfId.setText("Professor ID:");

        lblProfRating.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProfRating.setText("Professor Rating:");

        txtProfRating.setMinimumSize(new java.awt.Dimension(250, 22));
        txtProfRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfRatingActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDayAndTime)
                            .addComponent(lblProgramsFor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCredits)
                            .addComponent(lblCourseId)
                            .addComponent(lblCourseName)
                            .addComponent(lblCrn))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCourseId, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(txtCredits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDayAndTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAvailablePrograms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTerm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCourseName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCrn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTerm)
                                    .addComponent(lblRoomBuilding))
                                .addGap(50, 50, 50)
                                .addComponent(txtRoomBuilding, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(lblDegreesFor))
                                    .addComponent(lblProgram, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDegreesFor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblProfRating)
                                    .addComponent(lblProfName)
                                    .addComponent(lblProfId))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtProfId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtProfName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtProfRating, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(282, 282, 282))
            .addGroup(layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCrn)
                    .addComponent(txtCrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseName)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseId)
                    .addComponent(txtCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCredits))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDayAndTime)
                    .addComponent(txtDayAndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgramsFor)
                    .addComponent(txtAvailablePrograms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTerm, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoomBuilding)
                    .addComponent(txtRoomBuilding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProgram, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDegreesFor)
                    .addComponent(txtDegreesFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfName)
                    .addComponent(txtProfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfId)
                    .addComponent(txtProfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfRating)
                    .addComponent(txtProfRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProgramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProgramActionPerformed

    private void txtDegreesForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDegreesForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDegreesForActionPerformed

    private void txtProfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfNameActionPerformed

    private void txtProfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfIdActionPerformed

    private void txtProfRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfRatingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfRatingActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        
    workArea.remove(this);
    Component[] componentArray = workArea.getComponents();
    Component component = componentArray[componentArray.length - 1];
    if(component.toString().contains("StudentCourseJPanel")){
        StudentCourseJPanel panel = (StudentCourseJPanel) component;
        panel.populateTable();
    }else{
        StudentCourseRegistrationJPanel panel = (StudentCourseRegistrationJPanel) component;
        panel.populateTable();
    }
    CardLayout layout = (CardLayout) workArea.getLayout();
    layout.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCourseId;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblCredits;
    private javax.swing.JLabel lblCrn;
    private javax.swing.JLabel lblDayAndTime;
    private javax.swing.JLabel lblDegreesFor;
    private javax.swing.JLabel lblProfId;
    private javax.swing.JLabel lblProfName;
    private javax.swing.JLabel lblProfRating;
    private javax.swing.JLabel lblProgram;
    private javax.swing.JLabel lblProgramsFor;
    private javax.swing.JLabel lblRoomBuilding;
    private javax.swing.JLabel lblTerm;
    private javax.swing.JTextField txtAvailablePrograms;
    private javax.swing.JTextField txtCourseId;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCredits;
    private javax.swing.JTextField txtCrn;
    private javax.swing.JTextField txtDayAndTime;
    private javax.swing.JTextField txtDegreesFor;
    private javax.swing.JTextField txtProfId;
    private javax.swing.JTextField txtProfName;
    private javax.swing.JTextField txtProfRating;
    private javax.swing.JTextField txtProgram;
    private javax.swing.JTextField txtRoomBuilding;
    private javax.swing.JTextField txtTerm;
    // End of variables declaration//GEN-END:variables
}
