/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

//import java.awt.Checkbox;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import model.Patient;

/**
 *
 * @author Admin
 */

public class PatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientJPanel
     */
    Patient patient;
    ButtonGroup allergiesGroup;
    ButtonGroup onmedGroup;
    public PatientJPanel(Patient patient) {
        initComponents();
        this.patient = patient;
        
        allergiesGroup = new ButtonGroup(); 
        allergiesGroup.add(btnallyes); 
        allergiesGroup.add(btnallno);
        
        
  //      btnallno.setSelected(true); 
        
        onmedGroup = new ButtonGroup(); 
        onmedGroup.add(onmedyes); 
        onmedGroup.add(onmedno);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPatientTittle = new javax.swing.JLabel();
        lblpatientid = new javax.swing.JLabel();
        lblprimarydoctor = new javax.swing.JLabel();
        lbldocdateoflastvisit = new javax.swing.JLabel();
        lbldatenextappointment = new javax.swing.JLabel();
        lblallergies = new javax.swing.JLabel();
        lblonmedication = new javax.swing.JLabel();
        lblinsurancecoverage = new javax.swing.JLabel();
        txtpatientid = new javax.swing.JTextField();
        txtprimarydoctor = new javax.swing.JTextField();
        txtdocdateoflastvisit = new javax.swing.JTextField();
        txtdatenextappointment = new javax.swing.JTextField();
        txtinsurancecoverage = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnallyes = new javax.swing.JRadioButton();
        btnallno = new javax.swing.JRadioButton();
        onmedyes = new javax.swing.JRadioButton();
        onmedno = new javax.swing.JRadioButton();

        lblPatientTittle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPatientTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatientTittle.setText("Patient Detail");

        lblpatientid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpatientid.setText("Patient Id : ");

        lblprimarydoctor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblprimarydoctor.setText("Primary Doctor  :");

        lbldocdateoflastvisit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldocdateoflastvisit.setText("Doctor date of Last Appointment");

        lbldatenextappointment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldatenextappointment.setText("Date of Next Appointment :");

        lblallergies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblallergies.setText("Allergies  :");

        lblonmedication.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblonmedication.setText("On Medication : ");

        lblinsurancecoverage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblinsurancecoverage.setText("Insurance Coverage : ");

        txtprimarydoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprimarydoctorActionPerformed(evt);
            }
        });

        txtdocdateoflastvisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdocdateoflastvisitActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnallyes.setText("Yes");
        btnallyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnallyesActionPerformed(evt);
            }
        });

        btnallno.setText("No");

        onmedyes.setText("Yes");

        onmedno.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblinsurancecoverage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblonmedication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblallergies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbldatenextappointment, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(lblprimarydoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblpatientid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lbldocdateoflastvisit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtinsurancecoverage)
                        .addComponent(txtpatientid, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addComponent(txtprimarydoctor)
                        .addComponent(txtdocdateoflastvisit)
                        .addComponent(txtdatenextappointment))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnallyes)
                        .addGap(18, 18, 18)
                        .addComponent(btnallno))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(onmedyes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(onmedno)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPatientTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(btnSave)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPatientTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpatientid)
                    .addComponent(txtpatientid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprimarydoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblprimarydoctor))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdocdateoflastvisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldocdateoflastvisit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldatenextappointment)
                    .addComponent(txtdatenextappointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblallergies)
                    .addComponent(btnallyes)
                    .addComponent(btnallno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblonmedication)
                    .addComponent(onmedyes)
                    .addComponent(onmedno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinsurancecoverage)
                    .addComponent(txtinsurancecoverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnSave)
                .addContainerGap(10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        patient.setPatientid(txtpatientid.getText());
        patient.setPrimarydoctor(txtprimarydoctor.getText());
        patient.setDocdateoflastvisit(txtdocdateoflastvisit.getText());
        patient.setDatenextappointment(txtdatenextappointment.getText());
        //patient.setAllergies(txtallergies.getText());
        //patient.setOnmedication(txtonmed.getText());
        patient.setInsurancecoverage(txtinsurancecoverage.getText());
        //patient.setPerson(txtpatientid.getText());
        
        String allergies = btnallyes.isSelected() ? "Yes" : "No";
        patient.setAllergies(allergies);
         
        
        String onmedication = onmedyes.isSelected() ? "Yes" : "No";
        patient.setOnmedication(onmedication);
        
       
        
        JOptionPane.showMessageDialog(this,"Patient Detail Saved");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtprimarydoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprimarydoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprimarydoctorActionPerformed

    private void txtdocdateoflastvisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdocdateoflastvisitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdocdateoflastvisitActionPerformed

    private void btnallyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnallyesActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnallyesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JRadioButton btnallno;
    private javax.swing.JRadioButton btnallyes;
    private javax.swing.JLabel lblPatientTittle;
    private javax.swing.JLabel lblallergies;
    private javax.swing.JLabel lbldatenextappointment;
    private javax.swing.JLabel lbldocdateoflastvisit;
    private javax.swing.JLabel lblinsurancecoverage;
    private javax.swing.JLabel lblonmedication;
    private javax.swing.JLabel lblpatientid;
    private javax.swing.JLabel lblprimarydoctor;
    private javax.swing.JRadioButton onmedno;
    private javax.swing.JRadioButton onmedyes;
    private javax.swing.JTextField txtdatenextappointment;
    private javax.swing.JTextField txtdocdateoflastvisit;
    private javax.swing.JTextField txtinsurancecoverage;
    private javax.swing.JTextField txtpatientid;
    private javax.swing.JTextField txtprimarydoctor;
    // End of variables declaration//GEN-END:variables
}
